// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("mkdirat_bpf")
            .map("mkdir", false)
            .map("mkdirat_.bss", true)
            .prog("do_mkdirat");
        builder.build()
    }
    pub struct OpenMkdiratMaps<'obj> {
        pub mkdir: libbpf_rs::OpenMapMut<'obj>,
        pub bss: libbpf_rs::OpenMapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenMkdiratMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut mkdir = None;
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "mkdir" => mkdir = Some(map),
                    "mkdirat_.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                mkdir: mkdir.expect("map `mkdir` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(1)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct MkdiratMaps<'obj> {
        pub mkdir: libbpf_rs::MapMut<'obj>,
        pub bss: libbpf_rs::MapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> MkdiratMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut mkdir = None;
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "mkdir" => mkdir = Some(map),
                    "mkdirat_.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                mkdir: mkdir.expect("map `mkdir` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(1)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenMkdiratProgs<'obj> {
        pub do_mkdirat: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenMkdiratProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut do_mkdirat = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "do_mkdirat" => do_mkdirat = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                do_mkdirat: do_mkdirat.expect("prog `do_mkdirat` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct MkdiratProgs<'obj> {
        pub do_mkdirat: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> MkdiratProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenMkdiratProgs<'obj>) -> Self {
            Self {
                do_mkdirat: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.do_mkdirat.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct MkdiratSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> MkdiratSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenMkdiratSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenMkdiratSkel {
                maps: unsafe { OpenMkdiratMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenMkdiratProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for MkdiratSkelBuilder {
        type Output = OpenMkdiratSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenMkdiratSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenMkdiratSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 4],
            pub max_entries: *mut [i32; 1024],
            pub key: *mut i32,
            pub value: *mut i32,
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs {
            pub __anon_pt_regs_1: __anon_pt_regs_1,
            pub orig_x0: u64,
            pub syscallno: i32,
            pub unused2: u32,
            pub sdei_ttbr1: u64,
            pub pmr_save: u64,
            pub stackframe: [u64; 2],
            pub lockdep_hardirqs: u64,
            pub exit_rcu: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_pt_regs_1 {
            pub user_regs: user_pt_regs,
            pub __anon_pt_regs_3: __anon_pt_regs_3,
        }
        impl std::fmt::Debug for __anon_pt_regs_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_pt_regs_1 {
            fn default() -> Self {
                Self {
                    user_regs: user_pt_regs::default(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct user_pt_regs {
            pub regs: [u64; 31],
            pub sp: u64,
            pub pc: u64,
            pub pstate: u64,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_pt_regs_3 {
            pub regs: [u64; 31],
            pub sp: u64,
            pub pc: u64,
            pub pstate: u64,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct filename {
            pub name: *mut i8,
            pub uptr: *mut i8,
            pub refcnt: __anon_filename_1,
            pub __pad_20: [u8; 4],
            pub aname: *mut std::ffi::c_void,
            pub iname: [i8; 0],
        }
        impl Default for filename {
            fn default() -> Self {
                Self {
                    name: std::ptr::null_mut(),
                    uptr: std::ptr::null_mut(),
                    refcnt: __anon_filename_1::default(),
                    __pad_20: [u8::default(); 4],
                    aname: std::ptr::null_mut(),
                    iname: [i8::default(); 0],
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_filename_1 {
            pub counter: i32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct event {
            pub pid: i32,
            pub filename: [i8; 256],
            pub mode: u16,
        }
        impl Default for event {
            fn default() -> Self {
                Self {
                    pid: i32::default(),
                    filename: [i8::default(); 256],
                    mode: u16::default(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub dummy: event,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub mkdir: __anon_1,
        }
    }
    pub struct OpenMkdiratSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenMkdiratMaps<'obj>,
        pub progs: OpenMkdiratProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenMkdiratSkel<'obj> {
        type Output = MkdiratSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<MkdiratSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(MkdiratSkel {
                maps: unsafe { MkdiratMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: MkdiratProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: MkdiratLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct MkdiratLinks {
        pub do_mkdirat: Option<libbpf_rs::Link>,
    }
    pub struct MkdiratSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: MkdiratMaps<'obj>,
        pub progs: MkdiratProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: MkdiratLinks,
    }

    unsafe impl Send for MkdiratSkel<'_> {}
    unsafe impl Sync for MkdiratSkel<'_> {}

    impl<'obj> Skel<'obj> for MkdiratSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = MkdiratLinks {
                do_mkdirat: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl MkdiratSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 10, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 107, 112, 114, 111, 98, 101, 47, 100, 111, 95, 109, 107, 100, 105, 114, 97, 116, 0,
        46, 98, 115, 115, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 109, 97, 112, 115, 0, 109,
        107, 100, 105, 114, 97, 116, 46, 98, 112, 102, 46, 99, 0, 100, 111, 95, 109, 107, 100, 105,
        114, 97, 116, 0, 109, 107, 100, 105, 114, 0, 100, 117, 109, 109, 121, 0, 76, 73, 67, 69,
        78, 83, 69, 0, 46, 114, 101, 108, 107, 112, 114, 111, 98, 101, 47, 100, 111, 95, 109, 107,
        100, 105, 114, 97, 116, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 54, 0, 0, 0, 4, 0,
        241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 0, 0, 0, 0, 0, 79, 0, 0, 0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0,
        0, 0, 85, 0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 91, 0, 0,
        0, 17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 191, 22, 0, 0, 0, 0, 0, 0,
        121, 103, 8, 0, 0, 0, 0, 0, 121, 104, 16, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 183, 1,
        0, 0, 0, 0, 0, 0, 99, 26, 248, 255, 0, 0, 0, 0, 99, 26, 244, 255, 0, 0, 0, 0, 99, 26, 240,
        255, 0, 0, 0, 0, 99, 26, 236, 255, 0, 0, 0, 0, 99, 26, 232, 255, 0, 0, 0, 0, 99, 26, 228,
        255, 0, 0, 0, 0, 99, 26, 224, 255, 0, 0, 0, 0, 99, 26, 220, 255, 0, 0, 0, 0, 99, 26, 216,
        255, 0, 0, 0, 0, 99, 26, 212, 255, 0, 0, 0, 0, 99, 26, 208, 255, 0, 0, 0, 0, 99, 26, 204,
        255, 0, 0, 0, 0, 99, 26, 200, 255, 0, 0, 0, 0, 99, 26, 196, 255, 0, 0, 0, 0, 99, 26, 192,
        255, 0, 0, 0, 0, 99, 26, 188, 255, 0, 0, 0, 0, 99, 26, 184, 255, 0, 0, 0, 0, 99, 26, 180,
        255, 0, 0, 0, 0, 99, 26, 176, 255, 0, 0, 0, 0, 99, 26, 172, 255, 0, 0, 0, 0, 99, 26, 168,
        255, 0, 0, 0, 0, 99, 26, 164, 255, 0, 0, 0, 0, 99, 26, 160, 255, 0, 0, 0, 0, 99, 26, 156,
        255, 0, 0, 0, 0, 99, 26, 152, 255, 0, 0, 0, 0, 99, 26, 148, 255, 0, 0, 0, 0, 99, 26, 144,
        255, 0, 0, 0, 0, 99, 26, 140, 255, 0, 0, 0, 0, 99, 26, 136, 255, 0, 0, 0, 0, 99, 26, 132,
        255, 0, 0, 0, 0, 99, 26, 128, 255, 0, 0, 0, 0, 99, 26, 124, 255, 0, 0, 0, 0, 99, 26, 120,
        255, 0, 0, 0, 0, 99, 26, 116, 255, 0, 0, 0, 0, 99, 26, 112, 255, 0, 0, 0, 0, 99, 26, 108,
        255, 0, 0, 0, 0, 99, 26, 104, 255, 0, 0, 0, 0, 99, 26, 100, 255, 0, 0, 0, 0, 99, 26, 96,
        255, 0, 0, 0, 0, 99, 26, 92, 255, 0, 0, 0, 0, 99, 26, 88, 255, 0, 0, 0, 0, 99, 26, 84, 255,
        0, 0, 0, 0, 99, 26, 80, 255, 0, 0, 0, 0, 99, 26, 76, 255, 0, 0, 0, 0, 99, 26, 72, 255, 0,
        0, 0, 0, 99, 26, 68, 255, 0, 0, 0, 0, 99, 26, 64, 255, 0, 0, 0, 0, 99, 26, 60, 255, 0, 0,
        0, 0, 99, 26, 56, 255, 0, 0, 0, 0, 99, 26, 52, 255, 0, 0, 0, 0, 99, 26, 48, 255, 0, 0, 0,
        0, 99, 26, 44, 255, 0, 0, 0, 0, 99, 26, 40, 255, 0, 0, 0, 0, 99, 26, 36, 255, 0, 0, 0, 0,
        99, 26, 32, 255, 0, 0, 0, 0, 99, 26, 28, 255, 0, 0, 0, 0, 99, 26, 24, 255, 0, 0, 0, 0, 99,
        26, 20, 255, 0, 0, 0, 0, 99, 26, 16, 255, 0, 0, 0, 0, 99, 26, 12, 255, 0, 0, 0, 0, 99, 26,
        8, 255, 0, 0, 0, 0, 99, 26, 4, 255, 0, 0, 0, 0, 99, 26, 0, 255, 0, 0, 0, 0, 99, 26, 252,
        254, 0, 0, 0, 0, 99, 26, 252, 255, 0, 0, 0, 0, 107, 138, 252, 255, 0, 0, 0, 0, 119, 0, 0,
        0, 32, 0, 0, 0, 99, 10, 248, 254, 0, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 15, 23, 0, 0, 0, 0,
        0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 240, 254, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0,
        191, 115, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 113, 0, 0, 0, 121, 163, 240, 254, 0, 0, 0, 0,
        191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 252, 254, 255, 255, 183, 2, 0, 0, 0, 1, 0, 0, 133,
        0, 0, 0, 45, 0, 0, 0, 191, 164, 0, 0, 0, 0, 0, 0, 7, 4, 0, 0, 248, 254, 255, 255, 191, 97,
        0, 0, 0, 0, 0, 0, 24, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 3, 0, 0, 255, 255,
        255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 183, 5, 0, 0, 8, 1, 0, 0, 133, 0, 0, 0, 25, 0, 0, 0, 183,
        0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 2, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 112, 4, 0, 0,
        112, 4, 0, 0, 165, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4,
        0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0,
        0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 2, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        30, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 42, 0, 0, 0, 7, 0, 0, 0, 128, 0, 0, 0, 46, 0, 0, 0,
        7, 0, 0, 0, 192, 0, 0, 0, 52, 0, 0, 0, 0, 0, 0, 14, 8, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 11, 0, 0, 0, 58, 0, 0, 0, 9, 0, 0, 4, 80, 1, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0,
        0, 0, 66, 0, 0, 0, 18, 0, 0, 0, 128, 8, 0, 0, 74, 0, 0, 0, 20, 0, 0, 0, 192, 8, 0, 0, 84,
        0, 0, 0, 22, 0, 0, 0, 224, 8, 0, 0, 92, 0, 0, 0, 18, 0, 0, 0, 0, 9, 0, 0, 103, 0, 0, 0, 18,
        0, 0, 0, 64, 9, 0, 0, 112, 0, 0, 0, 25, 0, 0, 0, 128, 9, 0, 0, 123, 0, 0, 0, 18, 0, 0, 0,
        0, 10, 0, 0, 140, 0, 0, 0, 18, 0, 0, 0, 64, 10, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 16, 1, 0, 0,
        149, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 159, 0, 0, 0,
        4, 0, 0, 4, 16, 1, 0, 0, 172, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 177, 0, 0, 0, 14, 0, 0, 0,
        192, 7, 0, 0, 180, 0, 0, 0, 14, 0, 0, 0, 0, 8, 0, 0, 183, 0, 0, 0, 14, 0, 0, 0, 64, 8, 0,
        0, 190, 0, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 196, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 14, 0, 0, 0, 4, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 4,
        0, 0, 4, 16, 1, 0, 0, 172, 0, 0, 0, 19, 0, 0, 0, 0, 0, 0, 0, 177, 0, 0, 0, 18, 0, 0, 0,
        192, 7, 0, 0, 180, 0, 0, 0, 18, 0, 0, 0, 0, 8, 0, 0, 183, 0, 0, 0, 18, 0, 0, 0, 64, 8, 0,
        0, 215, 0, 0, 0, 0, 0, 0, 8, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 18, 0, 0, 0,
        4, 0, 0, 0, 31, 0, 0, 0, 219, 0, 0, 0, 0, 0, 0, 8, 21, 0, 0, 0, 223, 0, 0, 0, 0, 0, 0, 8,
        2, 0, 0, 0, 229, 0, 0, 0, 0, 0, 0, 8, 23, 0, 0, 0, 233, 0, 0, 0, 0, 0, 0, 8, 24, 0, 0, 0,
        239, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 18,
        0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 252, 0, 0, 0, 10, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 12, 26, 0, 0, 0, 11, 1, 0, 0, 5, 0, 0, 4, 32, 0, 0, 0, 20, 1, 0,
        0, 29, 0, 0, 0, 0, 0, 0, 0, 25, 1, 0, 0, 29, 0, 0, 0, 64, 0, 0, 0, 30, 1, 0, 0, 32, 0, 0,
        0, 128, 0, 0, 0, 37, 1, 0, 0, 34, 0, 0, 0, 192, 0, 0, 0, 43, 1, 0, 0, 35, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 2, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 31, 0, 0, 0, 49, 1, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 54, 1, 0, 0, 0, 0, 0, 8, 33, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 4, 4, 0, 0, 0, 63, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 45, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 30, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 71, 1, 0, 0, 3, 0,
        0, 4, 8, 1, 0, 0, 77, 1, 0, 0, 37, 0, 0, 0, 0, 0, 0, 0, 11, 1, 0, 0, 39, 0, 0, 0, 32, 0, 0,
        0, 81, 1, 0, 0, 40, 0, 0, 0, 32, 8, 0, 0, 86, 1, 0, 0, 0, 0, 0, 8, 38, 0, 0, 0, 92, 1, 0,
        0, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 31, 0, 0, 0, 4, 0, 0, 0, 0,
        1, 0, 0, 107, 1, 0, 0, 0, 0, 0, 8, 41, 0, 0, 0, 115, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16,
        0, 0, 0, 130, 1, 0, 0, 0, 0, 0, 14, 36, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0,
        0, 0, 31, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 136, 1, 0, 0, 0, 0, 0, 14, 43, 0, 0, 0, 1, 0, 0,
        0, 144, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 128, 3, 0, 0, 1, 0, 0, 15, 8, 1, 0, 0, 42, 0, 0,
        0, 0, 0, 0, 0, 8, 1, 0, 0, 133, 3, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 44, 0, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 0, 141, 3, 0, 0, 1, 0, 0, 15, 32, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0,
        105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95,
        95, 0, 116, 121, 112, 101, 0, 109, 97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 107,
        101, 121, 0, 118, 97, 108, 117, 101, 0, 109, 107, 100, 105, 114, 0, 112, 116, 95, 114, 101,
        103, 115, 0, 111, 114, 105, 103, 95, 120, 48, 0, 115, 121, 115, 99, 97, 108, 108, 110, 111,
        0, 117, 110, 117, 115, 101, 100, 50, 0, 115, 100, 101, 105, 95, 116, 116, 98, 114, 49, 0,
        112, 109, 114, 95, 115, 97, 118, 101, 0, 115, 116, 97, 99, 107, 102, 114, 97, 109, 101, 0,
        108, 111, 99, 107, 100, 101, 112, 95, 104, 97, 114, 100, 105, 114, 113, 115, 0, 101, 120,
        105, 116, 95, 114, 99, 117, 0, 117, 115, 101, 114, 95, 114, 101, 103, 115, 0, 117, 115,
        101, 114, 95, 112, 116, 95, 114, 101, 103, 115, 0, 114, 101, 103, 115, 0, 115, 112, 0, 112,
        99, 0, 112, 115, 116, 97, 116, 101, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103,
        110, 101, 100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0, 117, 54, 52, 0, 115, 51,
        50, 0, 95, 95, 115, 51, 50, 0, 117, 51, 50, 0, 95, 95, 117, 51, 50, 0, 117, 110, 115, 105,
        103, 110, 101, 100, 32, 105, 110, 116, 0, 99, 116, 120, 0, 100, 111, 95, 109, 107, 100,
        105, 114, 97, 116, 0, 102, 105, 108, 101, 110, 97, 109, 101, 0, 110, 97, 109, 101, 0, 117,
        112, 116, 114, 0, 114, 101, 102, 99, 110, 116, 0, 97, 110, 97, 109, 101, 0, 105, 110, 97,
        109, 101, 0, 99, 104, 97, 114, 0, 97, 116, 111, 109, 105, 99, 95, 116, 0, 99, 111, 117,
        110, 116, 101, 114, 0, 101, 118, 101, 110, 116, 0, 112, 105, 100, 0, 109, 111, 100, 101, 0,
        112, 105, 100, 95, 116, 0, 95, 95, 107, 101, 114, 110, 101, 108, 95, 112, 105, 100, 95,
        116, 0, 117, 109, 111, 100, 101, 95, 116, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32,
        115, 104, 111, 114, 116, 0, 100, 117, 109, 109, 121, 0, 76, 73, 67, 69, 78, 83, 69, 0, 97,
        117, 100, 105, 116, 95, 110, 97, 109, 101, 115, 0, 47, 104, 111, 109, 101, 47, 112, 104,
        105, 110, 103, 117, 121, 101, 110, 100, 112, 47, 87, 83, 45, 108, 105, 110, 117, 120, 47,
        101, 98, 112, 102, 47, 101, 101, 45, 101, 98, 112, 102, 47, 99, 104, 51, 95, 101, 98, 112,
        102, 95, 112, 114, 111, 98, 101, 115, 47, 109, 107, 100, 105, 114, 97, 116, 95, 112, 101,
        114, 102, 95, 101, 118, 101, 110, 116, 95, 97, 114, 114, 97, 121, 47, 115, 114, 99, 47, 98,
        112, 102, 47, 109, 107, 100, 105, 114, 97, 116, 46, 98, 112, 102, 46, 99, 0, 105, 110, 116,
        32, 66, 80, 70, 95, 75, 80, 82, 79, 66, 69, 40, 100, 111, 95, 109, 107, 100, 105, 114, 97,
        116, 44, 32, 105, 110, 116, 32, 100, 102, 100, 44, 32, 115, 116, 114, 117, 99, 116, 32,
        102, 105, 108, 101, 110, 97, 109, 101, 32, 42, 110, 97, 109, 101, 44, 32, 117, 109, 111,
        100, 101, 95, 116, 32, 109, 111, 100, 101, 41, 32, 123, 0, 9, 112, 105, 100, 95, 116, 32,
        112, 105, 100, 32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101,
        110, 116, 95, 112, 105, 100, 95, 116, 103, 105, 100, 40, 41, 32, 62, 62, 32, 51, 50, 59, 0,
        9, 115, 116, 114, 117, 99, 116, 32, 101, 118, 101, 110, 116, 32, 101, 118, 32, 61, 32, 123,
        125, 59, 0, 9, 101, 118, 46, 109, 111, 100, 101, 32, 61, 32, 109, 111, 100, 101, 59, 0, 9,
        101, 118, 46, 112, 105, 100, 32, 61, 32, 112, 105, 100, 59, 0, 9, 99, 111, 110, 115, 116,
        32, 99, 104, 97, 114, 32, 42, 102, 105, 108, 101, 110, 97, 109, 101, 32, 61, 32, 66, 80,
        70, 95, 67, 79, 82, 69, 95, 82, 69, 65, 68, 40, 110, 97, 109, 101, 44, 110, 97, 109, 101,
        41, 59, 0, 9, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 115,
        116, 114, 40, 101, 118, 46, 102, 105, 108, 101, 110, 97, 109, 101, 44, 32, 115, 105, 122,
        101, 111, 102, 40, 101, 118, 46, 102, 105, 108, 101, 110, 97, 109, 101, 41, 44, 32, 102,
        105, 108, 101, 110, 97, 109, 101, 41, 59, 0, 9, 98, 112, 102, 95, 112, 101, 114, 102, 95,
        101, 118, 101, 110, 116, 95, 111, 117, 116, 112, 117, 116, 40, 99, 116, 120, 44, 32, 38,
        109, 107, 100, 105, 114, 44, 32, 66, 80, 70, 95, 70, 95, 67, 85, 82, 82, 69, 78, 84, 95,
        67, 80, 85, 44, 32, 38, 101, 118, 44, 32, 115, 105, 122, 101, 111, 102, 40, 101, 118, 41,
        41, 59, 0, 48, 58, 48, 58, 49, 0, 48, 58, 48, 58, 50, 0, 48, 58, 48, 0, 46, 98, 115, 115,
        0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 109, 97, 112, 115, 0, 107, 112, 114, 111, 98,
        101, 47, 100, 111, 95, 109, 107, 100, 105, 114, 97, 116, 0, 0, 0, 0, 159, 235, 1, 0, 32, 0,
        0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 252, 0, 0, 0, 16, 1, 0, 0, 60, 0, 0, 0, 8, 0,
        0, 0, 147, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 16, 0, 0, 0, 147, 3, 0, 0, 15, 0,
        0, 0, 0, 0, 0, 0, 156, 1, 0, 0, 3, 2, 0, 0, 0, 108, 0, 0, 8, 0, 0, 0, 156, 1, 0, 0, 3, 2,
        0, 0, 5, 108, 0, 0, 24, 0, 0, 0, 156, 1, 0, 0, 78, 2, 0, 0, 14, 116, 0, 0, 40, 0, 0, 0,
        156, 1, 0, 0, 125, 2, 0, 0, 15, 120, 0, 0, 48, 2, 0, 0, 156, 1, 0, 0, 148, 2, 0, 0, 10,
        128, 0, 0, 56, 2, 0, 0, 156, 1, 0, 0, 78, 2, 0, 0, 41, 116, 0, 0, 64, 2, 0, 0, 156, 1, 0,
        0, 165, 2, 0, 0, 9, 124, 0, 0, 96, 2, 0, 0, 156, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104, 2,
        0, 0, 156, 1, 0, 0, 180, 2, 0, 0, 25, 132, 0, 0, 128, 2, 0, 0, 156, 1, 0, 0, 180, 2, 0, 0,
        25, 132, 0, 0, 136, 2, 0, 0, 156, 1, 0, 0, 125, 2, 0, 0, 15, 120, 0, 0, 152, 2, 0, 0, 156,
        1, 0, 0, 230, 2, 0, 0, 2, 136, 0, 0, 176, 2, 0, 0, 156, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        184, 2, 0, 0, 156, 1, 0, 0, 39, 3, 0, 0, 2, 144, 0, 0, 240, 2, 0, 0, 156, 1, 0, 0, 3, 2, 0,
        0, 5, 108, 0, 0, 16, 0, 0, 0, 147, 3, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 13, 0, 0, 0, 112, 3, 0,
        0, 0, 0, 0, 0, 16, 0, 0, 0, 13, 0, 0, 0, 118, 3, 0, 0, 0, 0, 0, 0, 72, 2, 0, 0, 28, 0, 0,
        0, 124, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 168, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0,
        0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 1, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 35, 0, 0, 0, 8, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 4, 0, 0,
        0, 0, 0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        112, 4, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 120, 4, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 152, 4, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
        3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 121, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 4, 0, 0, 0, 0, 0, 0, 45, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 126, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 12, 0, 0, 0, 0, 0, 0, 108,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0,
    ];
}
