// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("mkdirat_bpf")
            .map("mkdirat_.rodata", false)
            .prog("capture_mkdir");
        builder.build()
    }
    pub struct OpenMkdiratMaps<'obj> {
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenMkdiratMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "mkdirat_.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                rodata: rodata.expect("map `rodata` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct MkdiratMaps<'obj> {
        pub rodata: libbpf_rs::MapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> MkdiratMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "mkdirat_.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                rodata: rodata.expect("map `rodata` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenMkdiratProgs<'obj> {
        pub capture_mkdir: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenMkdiratProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut capture_mkdir = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "capture_mkdir" => capture_mkdir = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                capture_mkdir: capture_mkdir.expect("prog `capture_mkdir` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct MkdiratProgs<'obj> {
        pub capture_mkdir: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> MkdiratProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenMkdiratProgs<'obj>) -> Self {
            Self {
                capture_mkdir: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.capture_mkdir.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct MkdiratSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> MkdiratSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenMkdiratSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenMkdiratSkel {
                maps: unsafe { OpenMkdiratMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenMkdiratProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for MkdiratSkelBuilder {
        type Output = OpenMkdiratSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenMkdiratSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenMkdiratSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs {
            pub __anon_pt_regs_1: __anon_pt_regs_1,
            pub orig_x0: u64,
            pub syscallno: i32,
            pub unused2: u32,
            pub sdei_ttbr1: u64,
            pub pmr_save: u64,
            pub stackframe: [u64; 2],
            pub lockdep_hardirqs: u64,
            pub exit_rcu: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_pt_regs_1 {
            pub user_regs: user_pt_regs,
            pub __anon_pt_regs_3: __anon_pt_regs_3,
        }
        impl std::fmt::Debug for __anon_pt_regs_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_pt_regs_1 {
            fn default() -> Self {
                Self {
                    user_regs: user_pt_regs::default(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct user_pt_regs {
            pub regs: [u64; 31],
            pub sp: u64,
            pub pc: u64,
            pub pstate: u64,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_pt_regs_3 {
            pub regs: [u64; 31],
            pub sp: u64,
            pub pc: u64,
            pub pstate: u64,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct filename {
            pub name: *mut i8,
            pub uptr: *mut i8,
            pub refcnt: __anon_filename_1,
            pub __pad_20: [u8; 4],
            pub aname: *mut std::ffi::c_void,
            pub iname: [i8; 0],
        }
        impl Default for filename {
            fn default() -> Self {
                Self {
                    name: std::ptr::null_mut(),
                    uptr: std::ptr::null_mut(),
                    refcnt: __anon_filename_1::default(),
                    __pad_20: [u8::default(); 4],
                    aname: std::ptr::null_mut(),
                    iname: [i8::default(); 0],
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_filename_1 {
            pub counter: i32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {}
    }
    pub struct OpenMkdiratSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenMkdiratMaps<'obj>,
        pub progs: OpenMkdiratProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenMkdiratSkel<'obj> {
        type Output = MkdiratSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<MkdiratSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(MkdiratSkel {
                maps: unsafe { MkdiratMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: MkdiratProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: MkdiratLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct MkdiratLinks {
        pub capture_mkdir: Option<libbpf_rs::Link>,
    }
    pub struct MkdiratSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: MkdiratMaps<'obj>,
        pub progs: MkdiratProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: MkdiratLinks,
    }

    unsafe impl Send for MkdiratSkel<'_> {}
    unsafe impl Sync for MkdiratSkel<'_> {}

    impl<'obj> Skel<'obj> for MkdiratSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = MkdiratLinks {
                capture_mkdir: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl MkdiratSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 224, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 9, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98,
        0, 107, 112, 114, 111, 98, 101, 47, 100, 111, 95, 109, 107, 100, 105, 114, 97, 116, 0, 108,
        105, 99, 101, 110, 115, 101, 0, 46, 114, 111, 100, 97, 116, 97, 0, 109, 107, 100, 105, 114,
        97, 116, 46, 98, 112, 102, 46, 99, 0, 95, 95, 95, 95, 99, 97, 112, 116, 117, 114, 101, 95,
        109, 107, 100, 105, 114, 46, 95, 95, 95, 95, 102, 109, 116, 0, 99, 97, 112, 116, 117, 114,
        101, 95, 109, 107, 100, 105, 114, 0, 76, 73, 67, 69, 78, 83, 69, 0, 46, 114, 101, 108, 107,
        112, 114, 111, 98, 101, 47, 100, 111, 95, 109, 107, 100, 105, 114, 97, 116, 0, 46, 66, 84,
        70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 65, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 91, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 176, 0, 0, 0, 0, 0, 0, 0, 105, 0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 0, 0, 0, 0, 0, 121, 22, 16, 0, 0, 0, 0, 0, 121, 24, 8, 0, 0, 0, 0, 0, 133, 0, 0,
        0, 14, 0, 0, 0, 191, 7, 0, 0, 0, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 15, 24, 0, 0, 0, 0, 0,
        0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0,
        191, 131, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 113, 0, 0, 0, 87, 6, 0, 0, 255, 255, 0, 0, 121,
        164, 248, 255, 0, 0, 0, 0, 119, 7, 0, 0, 32, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 183, 2, 0, 0, 49, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 191, 101, 0, 0, 0, 0, 0,
        0, 133, 0, 0, 0, 6, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 71, 80,
        76, 0, 75, 80, 82, 79, 66, 69, 32, 69, 78, 84, 82, 89, 32, 112, 105, 100, 32, 61, 32, 37,
        100, 44, 32, 102, 105, 108, 101, 110, 97, 109, 101, 32, 61, 32, 37, 115, 44, 32, 109, 111,
        100, 101, 32, 61, 32, 37, 117, 10, 0, 0, 0, 0, 112, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0,
        0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 84, 3, 0, 0, 84, 3, 0, 0, 231, 2, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 9, 0, 0, 4, 80, 1, 0, 0, 0, 0, 0, 0, 3, 0, 0,
        0, 0, 0, 0, 0, 9, 0, 0, 0, 10, 0, 0, 0, 128, 8, 0, 0, 17, 0, 0, 0, 12, 0, 0, 0, 192, 8, 0,
        0, 27, 0, 0, 0, 15, 0, 0, 0, 224, 8, 0, 0, 35, 0, 0, 0, 10, 0, 0, 0, 0, 9, 0, 0, 46, 0, 0,
        0, 10, 0, 0, 0, 64, 9, 0, 0, 55, 0, 0, 0, 18, 0, 0, 0, 128, 9, 0, 0, 66, 0, 0, 0, 10, 0, 0,
        0, 0, 10, 0, 0, 83, 0, 0, 0, 10, 0, 0, 0, 64, 10, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 16, 1, 0,
        0, 92, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 102, 0, 0, 0,
        4, 0, 0, 4, 16, 1, 0, 0, 115, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 120, 0, 0, 0, 5, 0, 0, 0,
        192, 7, 0, 0, 123, 0, 0, 0, 5, 0, 0, 0, 0, 8, 0, 0, 126, 0, 0, 0, 5, 0, 0, 0, 64, 8, 0, 0,
        133, 0, 0, 0, 0, 0, 0, 8, 6, 0, 0, 0, 139, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 5, 0, 0, 0, 8, 0, 0, 0, 31, 0, 0, 0, 158, 0, 0, 0, 0, 0,
        0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 16, 1, 0, 0, 115, 0, 0, 0, 11, 0, 0,
        0, 0, 0, 0, 0, 120, 0, 0, 0, 10, 0, 0, 0, 192, 7, 0, 0, 123, 0, 0, 0, 10, 0, 0, 0, 0, 8, 0,
        0, 126, 0, 0, 0, 10, 0, 0, 0, 64, 8, 0, 0, 178, 0, 0, 0, 0, 0, 0, 8, 5, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 3, 0, 0, 0, 0, 10, 0, 0, 0, 8, 0, 0, 0, 31, 0, 0, 0, 182, 0, 0, 0, 0, 0, 0, 8,
        13, 0, 0, 0, 186, 0, 0, 0, 0, 0, 0, 8, 14, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0,
        32, 0, 0, 1, 196, 0, 0, 0, 0, 0, 0, 8, 16, 0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 8, 17, 0, 0, 0,
        206, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 10,
        0, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 14, 0, 0, 0, 219, 0, 0, 0, 1, 0,
        0, 0, 223, 0, 0, 0, 1, 0, 0, 12, 19, 0, 0, 0, 237, 0, 0, 0, 5, 0, 0, 4, 32, 0, 0, 0, 246,
        0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 251, 0, 0, 0, 22, 0, 0, 0, 64, 0, 0, 0, 0, 1, 0, 0, 25,
        0, 0, 0, 128, 0, 0, 0, 7, 1, 0, 0, 27, 0, 0, 0, 192, 0, 0, 0, 13, 1, 0, 0, 28, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 24, 0, 0, 0, 19, 1,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 24, 1, 0, 0, 0, 0, 0, 8, 26, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 4, 4, 0, 0, 0, 33, 1, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 33,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 23, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 3, 0, 0, 0, 0, 24, 0, 0, 0, 8, 0, 0, 0, 4, 0, 0, 0, 41, 1, 0, 0, 0, 0, 0, 14,
        29, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 23, 0, 0, 0, 8, 0, 0, 0, 49,
        0, 0, 0, 49, 1, 0, 0, 0, 0, 0, 14, 31, 0, 0, 0, 0, 0, 0, 0, 75, 1, 0, 0, 0, 0, 0, 7, 0, 0,
        0, 0, 197, 2, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 205, 2,
        0, 0, 1, 0, 0, 15, 49, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 112, 116, 95, 114,
        101, 103, 115, 0, 111, 114, 105, 103, 95, 120, 48, 0, 115, 121, 115, 99, 97, 108, 108, 110,
        111, 0, 117, 110, 117, 115, 101, 100, 50, 0, 115, 100, 101, 105, 95, 116, 116, 98, 114, 49,
        0, 112, 109, 114, 95, 115, 97, 118, 101, 0, 115, 116, 97, 99, 107, 102, 114, 97, 109, 101,
        0, 108, 111, 99, 107, 100, 101, 112, 95, 104, 97, 114, 100, 105, 114, 113, 115, 0, 101,
        120, 105, 116, 95, 114, 99, 117, 0, 117, 115, 101, 114, 95, 114, 101, 103, 115, 0, 117,
        115, 101, 114, 95, 112, 116, 95, 114, 101, 103, 115, 0, 114, 101, 103, 115, 0, 115, 112, 0,
        112, 99, 0, 112, 115, 116, 97, 116, 101, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105,
        103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0, 95, 95, 65, 82, 82,
        65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 117, 54, 52, 0, 115, 51, 50, 0,
        95, 95, 115, 51, 50, 0, 105, 110, 116, 0, 117, 51, 50, 0, 95, 95, 117, 51, 50, 0, 117, 110,
        115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 99, 116, 120, 0, 99, 97, 112, 116, 117,
        114, 101, 95, 109, 107, 100, 105, 114, 0, 102, 105, 108, 101, 110, 97, 109, 101, 0, 110,
        97, 109, 101, 0, 117, 112, 116, 114, 0, 114, 101, 102, 99, 110, 116, 0, 97, 110, 97, 109,
        101, 0, 105, 110, 97, 109, 101, 0, 99, 104, 97, 114, 0, 97, 116, 111, 109, 105, 99, 95,
        116, 0, 99, 111, 117, 110, 116, 101, 114, 0, 76, 73, 67, 69, 78, 83, 69, 0, 95, 95, 95, 95,
        99, 97, 112, 116, 117, 114, 101, 95, 109, 107, 100, 105, 114, 46, 95, 95, 95, 95, 102, 109,
        116, 0, 97, 117, 100, 105, 116, 95, 110, 97, 109, 101, 115, 0, 47, 104, 111, 109, 101, 47,
        112, 104, 105, 110, 103, 117, 121, 101, 110, 100, 112, 47, 87, 83, 45, 108, 105, 110, 117,
        120, 47, 101, 98, 112, 102, 47, 101, 101, 45, 101, 98, 112, 102, 47, 99, 104, 51, 95, 101,
        98, 112, 102, 95, 112, 114, 111, 98, 101, 115, 47, 109, 107, 100, 105, 114, 97, 116, 47,
        115, 114, 99, 47, 98, 112, 102, 47, 109, 107, 100, 105, 114, 97, 116, 46, 98, 112, 102, 46,
        99, 0, 105, 110, 116, 32, 66, 80, 70, 95, 75, 80, 82, 79, 66, 69, 40, 99, 97, 112, 116,
        117, 114, 101, 95, 109, 107, 100, 105, 114, 44, 32, 105, 110, 116, 32, 100, 102, 100, 44,
        32, 115, 116, 114, 117, 99, 116, 32, 102, 105, 108, 101, 110, 97, 109, 101, 32, 42, 110,
        97, 109, 101, 44, 32, 117, 109, 111, 100, 101, 95, 116, 32, 109, 111, 100, 101, 41, 0, 32,
        32, 32, 32, 32, 32, 32, 32, 112, 105, 100, 32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95,
        99, 117, 114, 114, 101, 110, 116, 95, 112, 105, 100, 95, 116, 103, 105, 100, 40, 41, 32,
        62, 62, 32, 51, 50, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 102, 105, 108, 101, 110, 97,
        109, 101, 32, 61, 32, 66, 80, 70, 95, 67, 79, 82, 69, 95, 82, 69, 65, 68, 40, 110, 97, 109,
        101, 44, 32, 110, 97, 109, 101, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 98, 112, 102,
        95, 112, 114, 105, 110, 116, 107, 40, 34, 75, 80, 82, 79, 66, 69, 32, 69, 78, 84, 82, 89,
        32, 112, 105, 100, 32, 61, 32, 37, 100, 44, 32, 102, 105, 108, 101, 110, 97, 109, 101, 32,
        61, 32, 37, 115, 44, 32, 109, 111, 100, 101, 32, 61, 32, 37, 117, 92, 110, 34, 44, 32, 112,
        105, 100, 44, 32, 102, 105, 108, 101, 110, 97, 109, 101, 44, 32, 109, 111, 100, 101, 41,
        59, 0, 48, 58, 48, 58, 50, 0, 48, 58, 48, 58, 49, 0, 48, 58, 48, 0, 108, 105, 99, 101, 110,
        115, 101, 0, 46, 114, 111, 100, 97, 116, 97, 0, 107, 112, 114, 111, 98, 101, 47, 100, 111,
        95, 109, 107, 100, 105, 114, 97, 116, 0, 0, 0, 0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0,
        0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 156, 0, 0, 0, 176, 0, 0, 0, 60, 0, 0, 0, 8, 0, 0, 0, 213,
        2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 16, 0, 0, 0, 213, 2, 0, 0, 9, 0, 0, 0, 0, 0,
        0, 0, 87, 1, 0, 0, 173, 1, 0, 0, 5, 112, 0, 0, 16, 0, 0, 0, 87, 1, 0, 0, 249, 1, 0, 0, 15,
        128, 0, 0, 56, 0, 0, 0, 87, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 87, 1, 0, 0, 41,
        2, 0, 0, 20, 132, 0, 0, 88, 0, 0, 0, 87, 1, 0, 0, 87, 2, 0, 0, 9, 136, 0, 0, 96, 0, 0, 0,
        87, 1, 0, 0, 41, 2, 0, 0, 20, 132, 0, 0, 104, 0, 0, 0, 87, 1, 0, 0, 249, 1, 0, 0, 42, 128,
        0, 0, 112, 0, 0, 0, 87, 1, 0, 0, 87, 2, 0, 0, 9, 136, 0, 0, 160, 0, 0, 0, 87, 1, 0, 0, 173,
        1, 0, 0, 5, 112, 0, 0, 16, 0, 0, 0, 213, 2, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 181,
        2, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 4, 0, 0, 0, 187, 2, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 21, 0,
        0, 0, 193, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 0, 0, 0, 0, 0, 0, 0, 168, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0,
        0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 1, 0, 0, 0, 0, 0, 0,
        176, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 35, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 2, 0, 0,
        0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 43, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        52, 2, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 113, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 104, 2, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0,
        8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 135, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 2, 0, 0, 0, 0, 0, 0, 83, 6, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 140, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 8, 0, 0, 0, 0, 0, 0, 12, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
