// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("pam_auth_bpf")
            .map("events", false)
            .map("authtok_ptrs", false)
            .map("user_ptrs", false)
            .map("pam_auth.bss", true)
            .prog("pam_get_authtok_enter")
            .prog("pam_get_authtok_exit")
            .prog("pam_get_user_enter")
            .prog("pam_get_user_exit");
        builder.build()
    }
    pub struct OpenPamAuthMaps<'obj> {
        pub events: libbpf_rs::OpenMapMut<'obj>,
        pub authtok_ptrs: libbpf_rs::OpenMapMut<'obj>,
        pub user_ptrs: libbpf_rs::OpenMapMut<'obj>,
        pub bss: libbpf_rs::OpenMapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenPamAuthMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut events = None;
            let mut authtok_ptrs = None;
            let mut user_ptrs = None;
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "events" => events = Some(map),
                    "authtok_ptrs" => authtok_ptrs = Some(map),
                    "user_ptrs" => user_ptrs = Some(map),
                    "pam_auth.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                events: events.expect("map `events` not present"),
                authtok_ptrs: authtok_ptrs.expect("map `authtok_ptrs` not present"),
                user_ptrs: user_ptrs.expect("map `user_ptrs` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(3)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct PamAuthMaps<'obj> {
        pub events: libbpf_rs::MapMut<'obj>,
        pub authtok_ptrs: libbpf_rs::MapMut<'obj>,
        pub user_ptrs: libbpf_rs::MapMut<'obj>,
        pub bss: libbpf_rs::MapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> PamAuthMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut events = None;
            let mut authtok_ptrs = None;
            let mut user_ptrs = None;
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "events" => events = Some(map),
                    "authtok_ptrs" => authtok_ptrs = Some(map),
                    "user_ptrs" => user_ptrs = Some(map),
                    "pam_auth.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                events: events.expect("map `events` not present"),
                authtok_ptrs: authtok_ptrs.expect("map `authtok_ptrs` not present"),
                user_ptrs: user_ptrs.expect("map `user_ptrs` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(3)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenPamAuthProgs<'obj> {
        pub pam_get_authtok_enter: libbpf_rs::OpenProgramMut<'obj>,
        pub pam_get_authtok_exit: libbpf_rs::OpenProgramMut<'obj>,
        pub pam_get_user_enter: libbpf_rs::OpenProgramMut<'obj>,
        pub pam_get_user_exit: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenPamAuthProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut pam_get_authtok_enter = None;
            let mut pam_get_authtok_exit = None;
            let mut pam_get_user_enter = None;
            let mut pam_get_user_exit = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "pam_get_authtok_enter" => pam_get_authtok_enter = Some(prog),
                    "pam_get_authtok_exit" => pam_get_authtok_exit = Some(prog),
                    "pam_get_user_enter" => pam_get_user_enter = Some(prog),
                    "pam_get_user_exit" => pam_get_user_exit = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                pam_get_authtok_enter: pam_get_authtok_enter
                    .expect("prog `pam_get_authtok_enter` not present"),
                pam_get_authtok_exit: pam_get_authtok_exit
                    .expect("prog `pam_get_authtok_exit` not present"),
                pam_get_user_enter: pam_get_user_enter
                    .expect("prog `pam_get_user_enter` not present"),
                pam_get_user_exit: pam_get_user_exit.expect("prog `pam_get_user_exit` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct PamAuthProgs<'obj> {
        pub pam_get_authtok_enter: libbpf_rs::ProgramMut<'obj>,
        pub pam_get_authtok_exit: libbpf_rs::ProgramMut<'obj>,
        pub pam_get_user_enter: libbpf_rs::ProgramMut<'obj>,
        pub pam_get_user_exit: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> PamAuthProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenPamAuthProgs<'obj>) -> Self {
            Self {
                pam_get_authtok_enter: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.pam_get_authtok_enter.as_libbpf_object().as_mut(),
                    )
                },
                pam_get_authtok_exit: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.pam_get_authtok_exit.as_libbpf_object().as_mut(),
                    )
                },
                pam_get_user_enter: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.pam_get_user_enter.as_libbpf_object().as_mut(),
                    )
                },
                pam_get_user_exit: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.pam_get_user_exit.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct PamAuthSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> PamAuthSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenPamAuthSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenPamAuthSkel {
                maps: unsafe { OpenPamAuthMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenPamAuthProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for PamAuthSkelBuilder {
        type Output = OpenPamAuthSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenPamAuthSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenPamAuthSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 27],
            pub max_entries: *mut [i32; 4096],
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_2 {
            pub r#type: *mut [i32; 1],
            pub max_entries: *mut [i32; 1024],
            pub key: *mut u32,
            pub value: *mut u64,
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs {
            pub r15: u64,
            pub r14: u64,
            pub r13: u64,
            pub r12: u64,
            pub bp: u64,
            pub bx: u64,
            pub r11: u64,
            pub r10: u64,
            pub r9: u64,
            pub r8: u64,
            pub ax: u64,
            pub cx: u64,
            pub dx: u64,
            pub si: u64,
            pub di: u64,
            pub orig_ax: u64,
            pub ip: u64,
            pub __anon_pt_regs_1: __anon_pt_regs_1,
            pub flags: u64,
            pub sp: u64,
            pub __anon_pt_regs_2: __anon_pt_regs_2,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_pt_regs_1 {
            pub cs: u16,
            pub csx: u64,
            pub fred_cs: fred_cs,
        }
        impl std::fmt::Debug for __anon_pt_regs_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_pt_regs_1 {
            fn default() -> Self {
                Self { cs: u16::default() }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_pt_regs_2 {
            pub ss: u16,
            pub ssx: u64,
            pub fred_ss: fred_ss,
        }
        impl std::fmt::Debug for __anon_pt_regs_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_pt_regs_2 {
            fn default() -> Self {
                Self { ss: u16::default() }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct fred_cs {
            pub __pad_0: [u8; 8],
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct fred_ss {
            pub __pad_0: [u8; 8],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct event {
            pub pid: i32,
            pub comm: [i8; 16],
            pub password: [i8; 128],
            pub username: [i8; 64],
        }
        impl Default for event {
            fn default() -> Self {
                Self {
                    pid: i32::default(),
                    comm: [i8::default(); 16],
                    password: [i8::default(); 128],
                    username: [i8::default(); 64],
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub dummy: event,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub events: __anon_1,
            pub authtok_ptrs: __anon_2,
            pub user_ptrs: __anon_2,
        }
    }
    pub struct OpenPamAuthSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenPamAuthMaps<'obj>,
        pub progs: OpenPamAuthProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenPamAuthSkel<'obj> {
        type Output = PamAuthSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<PamAuthSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(PamAuthSkel {
                maps: unsafe { PamAuthMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: PamAuthProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: PamAuthLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct PamAuthLinks {
        pub pam_get_authtok_enter: Option<libbpf_rs::Link>,
        pub pam_get_authtok_exit: Option<libbpf_rs::Link>,
        pub pam_get_user_enter: Option<libbpf_rs::Link>,
        pub pam_get_user_exit: Option<libbpf_rs::Link>,
    }
    pub struct PamAuthSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: PamAuthMaps<'obj>,
        pub progs: PamAuthProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: PamAuthLinks,
    }

    unsafe impl Send for PamAuthSkel<'_> {}
    unsafe impl Sync for PamAuthSkel<'_> {}

    impl<'obj> Skel<'obj> for PamAuthSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = PamAuthLinks {
                pam_get_authtok_enter: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                pam_get_authtok_exit: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(1)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                pam_get_user_enter: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(2)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
                pam_get_user_exit: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(3)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl PamAuthSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 16, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 117, 112, 114, 111, 98, 101, 47, 47, 108, 105, 98, 47, 120, 56, 54, 95, 54, 52, 45,
        108, 105, 110, 117, 120, 45, 103, 110, 117, 47, 108, 105, 98, 112, 97, 109, 46, 115, 111,
        46, 48, 58, 112, 97, 109, 95, 103, 101, 116, 95, 97, 117, 116, 104, 116, 111, 107, 0, 117,
        114, 101, 116, 112, 114, 111, 98, 101, 47, 47, 108, 105, 98, 47, 120, 56, 54, 95, 54, 52,
        45, 108, 105, 110, 117, 120, 45, 103, 110, 117, 47, 108, 105, 98, 112, 97, 109, 46, 115,
        111, 46, 48, 58, 112, 97, 109, 95, 103, 101, 116, 95, 97, 117, 116, 104, 116, 111, 107, 0,
        117, 112, 114, 111, 98, 101, 47, 47, 108, 105, 98, 47, 120, 56, 54, 95, 54, 52, 45, 108,
        105, 110, 117, 120, 45, 103, 110, 117, 47, 108, 105, 98, 112, 97, 109, 46, 115, 111, 46,
        48, 58, 112, 97, 109, 95, 103, 101, 116, 95, 117, 115, 101, 114, 0, 117, 114, 101, 116,
        112, 114, 111, 98, 101, 47, 47, 108, 105, 98, 47, 120, 56, 54, 95, 54, 52, 45, 108, 105,
        110, 117, 120, 45, 103, 110, 117, 47, 108, 105, 98, 112, 97, 109, 46, 115, 111, 46, 48, 58,
        112, 97, 109, 95, 103, 101, 116, 95, 117, 115, 101, 114, 0, 108, 105, 99, 101, 110, 115,
        101, 0, 46, 98, 115, 115, 0, 46, 109, 97, 112, 115, 0, 112, 97, 109, 95, 97, 117, 116, 104,
        46, 98, 112, 102, 46, 99, 0, 112, 97, 109, 95, 103, 101, 116, 95, 97, 117, 116, 104, 116,
        111, 107, 95, 101, 110, 116, 101, 114, 0, 97, 117, 116, 104, 116, 111, 107, 95, 112, 116,
        114, 115, 0, 112, 97, 109, 95, 103, 101, 116, 95, 97, 117, 116, 104, 116, 111, 107, 95,
        101, 120, 105, 116, 0, 101, 118, 101, 110, 116, 115, 0, 112, 97, 109, 95, 103, 101, 116,
        95, 117, 115, 101, 114, 95, 101, 110, 116, 101, 114, 0, 117, 115, 101, 114, 95, 112, 116,
        114, 115, 0, 112, 97, 109, 95, 103, 101, 116, 95, 117, 115, 101, 114, 95, 101, 120, 105,
        116, 0, 76, 73, 67, 69, 78, 83, 69, 0, 100, 117, 109, 109, 121, 0, 46, 114, 101, 108, 117,
        112, 114, 111, 98, 101, 47, 47, 108, 105, 98, 47, 120, 56, 54, 95, 54, 52, 45, 108, 105,
        110, 117, 120, 45, 103, 110, 117, 47, 108, 105, 98, 112, 97, 109, 46, 115, 111, 46, 48, 58,
        112, 97, 109, 95, 103, 101, 116, 95, 97, 117, 116, 104, 116, 111, 107, 0, 46, 114, 101,
        108, 117, 114, 101, 116, 112, 114, 111, 98, 101, 47, 47, 108, 105, 98, 47, 120, 56, 54, 95,
        54, 52, 45, 108, 105, 110, 117, 120, 45, 103, 110, 117, 47, 108, 105, 98, 112, 97, 109, 46,
        115, 111, 46, 48, 58, 112, 97, 109, 95, 103, 101, 116, 95, 97, 117, 116, 104, 116, 111,
        107, 0, 46, 114, 101, 108, 117, 112, 114, 111, 98, 101, 47, 47, 108, 105, 98, 47, 120, 56,
        54, 95, 54, 52, 45, 108, 105, 110, 117, 120, 45, 103, 110, 117, 47, 108, 105, 98, 112, 97,
        109, 46, 115, 111, 46, 48, 58, 112, 97, 109, 95, 103, 101, 116, 95, 117, 115, 101, 114, 0,
        46, 114, 101, 108, 117, 114, 101, 116, 112, 114, 111, 98, 101, 47, 47, 108, 105, 98, 47,
        120, 56, 54, 95, 54, 52, 45, 108, 105, 110, 117, 120, 45, 103, 110, 117, 47, 108, 105, 98,
        112, 97, 109, 46, 115, 111, 46, 48, 58, 112, 97, 109, 95, 103, 101, 116, 95, 117, 115, 101,
        114, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0, 4, 0, 241, 255, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 1, 0, 0, 18, 0, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 45, 1, 0, 0, 17, 0, 9, 0, 16, 0, 0, 0, 0, 0, 0, 0,
        32, 0, 0, 0, 0, 0, 0, 0, 58, 1, 0, 0, 18, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 1, 0, 0, 0,
        0, 0, 0, 79, 1, 0, 0, 17, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 86, 1,
        0, 0, 18, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 105, 1, 0, 0, 17, 0,
        9, 0, 48, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 115, 1, 0, 0, 18, 0, 6, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 160, 1, 0, 0, 0, 0, 0, 0, 133, 1, 0, 0, 17, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 0, 0, 0, 0, 0, 141, 1, 0, 0, 17, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 212, 0, 0, 0, 0,
        0, 0, 0, 121, 22, 96, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0,
        99, 10, 252, 255, 0, 0, 0, 0, 123, 106, 240, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0,
        7, 2, 0, 0, 252, 255, 255, 255, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 240, 255, 255, 255,
        24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 2,
        0, 0, 0, 180, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 191, 22, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 14, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 99, 10, 252, 255, 0, 0, 0, 0, 121,
        103, 80, 0, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 252, 255, 255, 255, 24, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0, 0, 191, 6, 0, 0, 0, 0, 0,
        0, 21, 6, 38, 0, 0, 0, 0, 0, 103, 7, 0, 0, 32, 0, 0, 0, 119, 7, 0, 0, 32, 0, 0, 0, 191,
        162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 252, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 133, 0, 0, 0, 3, 0, 0, 0, 85, 7, 30, 0, 0, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0,
        123, 26, 240, 255, 0, 0, 0, 0, 121, 99, 0, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1,
        0, 0, 240, 255, 255, 255, 180, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 121, 161,
        240, 255, 0, 0, 0, 0, 21, 1, 21, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 183, 2, 0, 0, 212, 0, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0, 21,
        0, 15, 0, 0, 0, 0, 0, 97, 161, 252, 255, 0, 0, 0, 0, 99, 16, 0, 0, 0, 0, 0, 0, 191, 1, 0,
        0, 0, 0, 0, 0, 7, 1, 0, 0, 4, 0, 0, 0, 180, 2, 0, 0, 16, 0, 0, 0, 191, 6, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 16, 0, 0, 0, 121, 163, 240, 255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1,
        0, 0, 20, 0, 0, 0, 180, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 191, 97, 0, 0,
        0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 180, 0, 0, 0, 0, 0, 0, 0,
        149, 0, 0, 0, 0, 0, 0, 0, 121, 22, 104, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 119, 0,
        0, 0, 32, 0, 0, 0, 99, 10, 252, 255, 0, 0, 0, 0, 123, 106, 240, 255, 0, 0, 0, 0, 191, 162,
        0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 252, 255, 255, 255, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0,
        240, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0,
        0, 133, 0, 0, 0, 2, 0, 0, 0, 180, 0, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 191, 22,
        0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 99, 10, 252, 255,
        0, 0, 0, 0, 121, 103, 80, 0, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 252, 255,
        255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0, 0, 191,
        6, 0, 0, 0, 0, 0, 0, 21, 6, 38, 0, 0, 0, 0, 0, 103, 7, 0, 0, 32, 0, 0, 0, 119, 7, 0, 0, 32,
        0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 252, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 3, 0, 0, 0, 85, 7, 30, 0, 0, 0, 0, 0, 183, 1, 0,
        0, 0, 0, 0, 0, 123, 26, 240, 255, 0, 0, 0, 0, 121, 99, 0, 0, 0, 0, 0, 0, 191, 161, 0, 0, 0,
        0, 0, 0, 7, 1, 0, 0, 240, 255, 255, 255, 180, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0,
        0, 121, 161, 240, 255, 0, 0, 0, 0, 21, 1, 21, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 212, 0, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131,
        0, 0, 0, 21, 0, 15, 0, 0, 0, 0, 0, 97, 161, 252, 255, 0, 0, 0, 0, 99, 16, 0, 0, 0, 0, 0, 0,
        191, 1, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 4, 0, 0, 0, 180, 2, 0, 0, 16, 0, 0, 0, 191, 6, 0, 0,
        0, 0, 0, 0, 133, 0, 0, 0, 16, 0, 0, 0, 121, 163, 240, 255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0,
        0, 0, 7, 1, 0, 0, 148, 0, 0, 0, 180, 2, 0, 0, 64, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 191,
        97, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 180, 0, 0, 0,
        0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 56, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0,
        232, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 9, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 11,
        0, 0, 0, 56, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 11, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 11, 0, 0, 0, 232, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 9, 0, 0, 0, 159, 235, 1, 0, 24, 0,
        0, 0, 0, 0, 0, 0, 108, 5, 0, 0, 108, 5, 0, 0, 127, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0,
        2, 0, 0, 0, 4, 0, 0, 0, 27, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0,
        0, 16, 0, 0, 0, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30,
        0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 42, 0, 0, 0, 0, 0, 0, 14, 7, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0,
        0, 0, 4, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 14, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 8,
        15, 0, 0, 0, 55, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 17,
        0, 0, 0, 68, 0, 0, 0, 0, 0, 0, 8, 18, 0, 0, 0, 74, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0,
        0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 25, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0,
        0, 11, 0, 0, 0, 64, 0, 0, 0, 93, 0, 0, 0, 13, 0, 0, 0, 128, 0, 0, 0, 97, 0, 0, 0, 16, 0, 0,
        0, 192, 0, 0, 0, 103, 0, 0, 0, 0, 0, 0, 14, 19, 0, 0, 0, 1, 0, 0, 0, 116, 0, 0, 0, 0, 0, 0,
        14, 19, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 23, 0, 0, 0, 126, 0, 0, 0, 21, 0, 0,
        4, 168, 0, 0, 0, 134, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 138, 0, 0, 0, 24, 0, 0, 0, 64, 0,
        0, 0, 142, 0, 0, 0, 24, 0, 0, 0, 128, 0, 0, 0, 146, 0, 0, 0, 24, 0, 0, 0, 192, 0, 0, 0,
        150, 0, 0, 0, 24, 0, 0, 0, 0, 1, 0, 0, 153, 0, 0, 0, 24, 0, 0, 0, 64, 1, 0, 0, 156, 0, 0,
        0, 24, 0, 0, 0, 128, 1, 0, 0, 160, 0, 0, 0, 24, 0, 0, 0, 192, 1, 0, 0, 164, 0, 0, 0, 24, 0,
        0, 0, 0, 2, 0, 0, 167, 0, 0, 0, 24, 0, 0, 0, 64, 2, 0, 0, 170, 0, 0, 0, 24, 0, 0, 0, 128,
        2, 0, 0, 173, 0, 0, 0, 24, 0, 0, 0, 192, 2, 0, 0, 176, 0, 0, 0, 24, 0, 0, 0, 0, 3, 0, 0,
        179, 0, 0, 0, 24, 0, 0, 0, 64, 3, 0, 0, 182, 0, 0, 0, 24, 0, 0, 0, 128, 3, 0, 0, 185, 0, 0,
        0, 24, 0, 0, 0, 192, 3, 0, 0, 193, 0, 0, 0, 24, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 25, 0, 0,
        0, 64, 4, 0, 0, 196, 0, 0, 0, 24, 0, 0, 0, 128, 4, 0, 0, 202, 0, 0, 0, 24, 0, 0, 0, 192, 4,
        0, 0, 0, 0, 0, 0, 31, 0, 0, 0, 0, 5, 0, 0, 205, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 5, 8, 0, 0, 0, 219, 0, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 222, 0, 0, 0,
        29, 0, 0, 0, 0, 0, 0, 0, 226, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 234, 0, 0, 0, 0, 0, 0, 8,
        27, 0, 0, 0, 238, 0, 0, 0, 0, 0, 0, 8, 28, 0, 0, 0, 244, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0,
        16, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 8, 17, 0, 0, 0, 226, 0, 0, 0, 3, 0, 0, 132, 8, 0, 0, 0,
        219, 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 16, 7, 1, 0, 0, 29, 0, 0, 0, 16, 0, 0, 2, 10, 1, 0, 0,
        29, 0, 0, 0, 18, 0, 0, 1, 0, 0, 0, 0, 3, 0, 0, 5, 8, 0, 0, 0, 14, 1, 0, 0, 26, 0, 0, 0, 0,
        0, 0, 0, 17, 1, 0, 0, 29, 0, 0, 0, 0, 0, 0, 0, 21, 1, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 21, 1,
        0, 0, 10, 0, 0, 132, 8, 0, 0, 0, 14, 1, 0, 0, 29, 0, 0, 0, 0, 0, 0, 16, 29, 1, 0, 0, 29, 0,
        0, 0, 16, 0, 0, 1, 33, 1, 0, 0, 29, 0, 0, 0, 17, 0, 0, 1, 41, 1, 0, 0, 29, 0, 0, 0, 18, 0,
        0, 1, 45, 1, 0, 0, 29, 0, 0, 0, 32, 0, 0, 8, 25, 0, 0, 0, 29, 0, 0, 0, 48, 0, 0, 4, 52, 1,
        0, 0, 29, 0, 0, 0, 56, 0, 0, 1, 60, 1, 0, 0, 29, 0, 0, 0, 57, 0, 0, 1, 63, 1, 0, 0, 29, 0,
        0, 0, 58, 0, 0, 1, 70, 1, 0, 0, 29, 0, 0, 0, 60, 0, 0, 4, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0,
        0, 78, 1, 0, 0, 22, 0, 0, 0, 82, 1, 0, 0, 1, 0, 0, 12, 33, 0, 0, 0, 104, 1, 0, 0, 1, 0, 0,
        12, 33, 0, 0, 0, 125, 1, 0, 0, 1, 0, 0, 12, 33, 0, 0, 0, 144, 1, 0, 0, 1, 0, 0, 12, 33, 0,
        0, 0, 162, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0,
        38, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 167, 1, 0, 0, 0, 0, 0, 14, 39, 0, 0, 0, 1, 0, 0, 0,
        175, 1, 0, 0, 4, 0, 0, 4, 212, 0, 0, 0, 181, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 185, 1, 0, 0,
        42, 0, 0, 0, 32, 0, 0, 0, 190, 1, 0, 0, 43, 0, 0, 0, 160, 0, 0, 0, 199, 1, 0, 0, 44, 0, 0,
        0, 160, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 38, 0, 0, 0, 4, 0, 0, 0, 16, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 38, 0, 0, 0, 4, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 3, 0, 0, 0, 0, 38, 0, 0, 0, 4, 0, 0, 0, 64, 0, 0, 0, 208, 1, 0, 0, 0, 0, 0, 14, 41,
        0, 0, 0, 1, 0, 0, 0, 136, 7, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 4, 0,
        0, 0, 144, 7, 0, 0, 1, 0, 0, 15, 212, 0, 0, 0, 45, 0, 0, 0, 0, 0, 0, 0, 212, 0, 0, 0, 149,
        7, 0, 0, 3, 0, 0, 15, 80, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 20, 0, 0, 0, 16, 0,
        0, 0, 32, 0, 0, 0, 21, 0, 0, 0, 48, 0, 0, 0, 32, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95, 65,
        82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 116, 121, 112, 101, 0,
        109, 97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 101, 118, 101, 110, 116, 115, 0,
        95, 95, 117, 51, 50, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 95,
        95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32,
        108, 111, 110, 103, 0, 107, 101, 121, 0, 118, 97, 108, 117, 101, 0, 97, 117, 116, 104, 116,
        111, 107, 95, 112, 116, 114, 115, 0, 117, 115, 101, 114, 95, 112, 116, 114, 115, 0, 112,
        116, 95, 114, 101, 103, 115, 0, 114, 49, 53, 0, 114, 49, 52, 0, 114, 49, 51, 0, 114, 49,
        50, 0, 98, 112, 0, 98, 120, 0, 114, 49, 49, 0, 114, 49, 48, 0, 114, 57, 0, 114, 56, 0, 97,
        120, 0, 99, 120, 0, 100, 120, 0, 115, 105, 0, 100, 105, 0, 111, 114, 105, 103, 95, 97, 120,
        0, 105, 112, 0, 102, 108, 97, 103, 115, 0, 115, 112, 0, 117, 110, 115, 105, 103, 110, 101,
        100, 32, 108, 111, 110, 103, 0, 99, 115, 0, 99, 115, 120, 0, 102, 114, 101, 100, 95, 99,
        115, 0, 117, 49, 54, 0, 95, 95, 117, 49, 54, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32,
        115, 104, 111, 114, 116, 0, 117, 54, 52, 0, 115, 108, 0, 119, 102, 101, 0, 115, 115, 0,
        115, 115, 120, 0, 102, 114, 101, 100, 95, 115, 115, 0, 115, 116, 105, 0, 115, 119, 101,
        118, 101, 110, 116, 0, 110, 109, 105, 0, 118, 101, 99, 116, 111, 114, 0, 101, 110, 99, 108,
        97, 118, 101, 0, 108, 109, 0, 110, 101, 115, 116, 101, 100, 0, 105, 110, 115, 110, 108,
        101, 110, 0, 99, 116, 120, 0, 112, 97, 109, 95, 103, 101, 116, 95, 97, 117, 116, 104, 116,
        111, 107, 95, 101, 110, 116, 101, 114, 0, 112, 97, 109, 95, 103, 101, 116, 95, 97, 117,
        116, 104, 116, 111, 107, 95, 101, 120, 105, 116, 0, 112, 97, 109, 95, 103, 101, 116, 95,
        117, 115, 101, 114, 95, 101, 110, 116, 101, 114, 0, 112, 97, 109, 95, 103, 101, 116, 95,
        117, 115, 101, 114, 95, 101, 120, 105, 116, 0, 99, 104, 97, 114, 0, 76, 73, 67, 69, 78, 83,
        69, 0, 101, 118, 101, 110, 116, 0, 112, 105, 100, 0, 99, 111, 109, 109, 0, 112, 97, 115,
        115, 119, 111, 114, 100, 0, 117, 115, 101, 114, 110, 97, 109, 101, 0, 100, 117, 109, 109,
        121, 0, 47, 104, 111, 109, 101, 47, 112, 104, 105, 110, 103, 117, 121, 101, 110, 100, 112,
        47, 82, 117, 115, 116, 47, 101, 101, 45, 101, 98, 112, 102, 47, 99, 104, 51, 95, 101, 98,
        112, 102, 95, 112, 114, 111, 98, 101, 115, 47, 112, 97, 109, 95, 97, 117, 116, 104, 47,
        115, 114, 99, 47, 98, 112, 102, 47, 112, 97, 109, 95, 97, 117, 116, 104, 46, 98, 112, 102,
        46, 99, 0, 105, 110, 116, 32, 66, 80, 70, 95, 85, 80, 82, 79, 66, 69, 40, 112, 97, 109, 95,
        103, 101, 116, 95, 97, 117, 116, 104, 116, 111, 107, 95, 101, 110, 116, 101, 114, 44, 32,
        0, 9, 112, 105, 100, 95, 116, 32, 112, 105, 100, 32, 61, 32, 98, 112, 102, 95, 103, 101,
        116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 112, 105, 100, 95, 116, 103, 105, 100, 40,
        41, 32, 62, 62, 32, 51, 50, 59, 0, 9, 95, 95, 117, 54, 52, 32, 97, 116, 111, 107, 95, 112,
        116, 114, 32, 61, 32, 40, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103,
        41, 97, 117, 116, 104, 116, 111, 107, 59, 0, 9, 98, 112, 102, 95, 109, 97, 112, 95, 117,
        112, 100, 97, 116, 101, 95, 101, 108, 101, 109, 40, 38, 97, 117, 116, 104, 116, 111, 107,
        95, 112, 116, 114, 115, 44, 32, 38, 112, 105, 100, 44, 32, 38, 97, 116, 111, 107, 95, 112,
        116, 114, 44, 32, 66, 80, 70, 95, 65, 78, 89, 41, 59, 0, 105, 110, 116, 32, 66, 80, 70, 95,
        85, 82, 69, 84, 80, 82, 79, 66, 69, 40, 112, 97, 109, 95, 103, 101, 116, 95, 97, 117, 116,
        104, 116, 111, 107, 95, 101, 120, 105, 116, 41, 0, 32, 32, 32, 32, 112, 105, 100, 95, 116,
        32, 112, 105, 100, 32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101,
        110, 116, 95, 112, 105, 100, 95, 116, 103, 105, 100, 40, 41, 32, 62, 62, 32, 51, 50, 59, 0,
        32, 32, 32, 32, 105, 110, 116, 32, 114, 101, 116, 32, 61, 32, 80, 84, 95, 82, 69, 71, 83,
        95, 82, 67, 40, 99, 116, 120, 41, 59, 0, 32, 32, 32, 32, 95, 95, 117, 54, 52, 32, 42, 115,
        116, 111, 114, 101, 100, 32, 61, 32, 98, 112, 102, 95, 109, 97, 112, 95, 108, 111, 111,
        107, 117, 112, 95, 101, 108, 101, 109, 40, 38, 97, 117, 116, 104, 116, 111, 107, 95, 112,
        116, 114, 115, 44, 32, 38, 112, 105, 100, 41, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 33,
        115, 116, 111, 114, 101, 100, 41, 0, 32, 32, 32, 32, 98, 112, 102, 95, 109, 97, 112, 95,
        100, 101, 108, 101, 116, 101, 95, 101, 108, 101, 109, 40, 38, 97, 117, 116, 104, 116, 111,
        107, 95, 112, 116, 114, 115, 44, 32, 38, 112, 105, 100, 41, 59, 0, 32, 32, 32, 32, 105,
        102, 32, 40, 114, 101, 116, 32, 33, 61, 32, 48, 41, 0, 32, 32, 32, 32, 95, 95, 117, 54, 52,
        32, 97, 116, 111, 107, 95, 97, 100, 100, 114, 32, 61, 32, 48, 59, 0, 32, 32, 32, 32, 98,
        112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101, 114, 40,
        38, 97, 116, 111, 107, 95, 97, 100, 100, 114, 44, 32, 115, 105, 122, 101, 111, 102, 40, 97,
        116, 111, 107, 95, 97, 100, 100, 114, 41, 44, 32, 40, 99, 111, 110, 115, 116, 32, 118, 111,
        105, 100, 32, 42, 41, 40, 42, 115, 116, 111, 114, 101, 100, 41, 41, 59, 0, 32, 32, 32, 32,
        105, 102, 32, 40, 33, 97, 116, 111, 107, 95, 97, 100, 100, 114, 41, 0, 32, 32, 32, 32, 115,
        116, 114, 117, 99, 116, 32, 101, 118, 101, 110, 116, 32, 42, 101, 118, 116, 32, 61, 32, 98,
        112, 102, 95, 114, 105, 110, 103, 98, 117, 102, 95, 114, 101, 115, 101, 114, 118, 101, 40,
        38, 101, 118, 101, 110, 116, 115, 44, 32, 115, 105, 122, 101, 111, 102, 40, 115, 116, 114,
        117, 99, 116, 32, 101, 118, 101, 110, 116, 41, 44, 32, 48, 41, 59, 0, 32, 32, 32, 32, 105,
        102, 32, 40, 33, 101, 118, 116, 41, 0, 32, 32, 32, 32, 101, 118, 116, 45, 62, 112, 105,
        100, 32, 61, 32, 112, 105, 100, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 103, 101, 116, 95,
        99, 117, 114, 114, 101, 110, 116, 95, 99, 111, 109, 109, 40, 38, 101, 118, 116, 45, 62, 99,
        111, 109, 109, 44, 32, 115, 105, 122, 101, 111, 102, 40, 101, 118, 116, 45, 62, 99, 111,
        109, 109, 41, 41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114,
        101, 97, 100, 95, 117, 115, 101, 114, 40, 101, 118, 116, 45, 62, 112, 97, 115, 115, 119,
        111, 114, 100, 44, 32, 115, 105, 122, 101, 111, 102, 40, 101, 118, 116, 45, 62, 112, 97,
        115, 115, 119, 111, 114, 100, 41, 44, 32, 40, 99, 111, 110, 115, 116, 32, 118, 111, 105,
        100, 32, 42, 41, 97, 116, 111, 107, 95, 97, 100, 100, 114, 41, 59, 0, 32, 32, 32, 32, 98,
        112, 102, 95, 114, 105, 110, 103, 98, 117, 102, 95, 115, 117, 98, 109, 105, 116, 40, 101,
        118, 116, 44, 32, 48, 41, 59, 0, 105, 110, 116, 32, 66, 80, 70, 95, 85, 80, 82, 79, 66, 69,
        40, 112, 97, 109, 95, 103, 101, 116, 95, 117, 115, 101, 114, 95, 101, 110, 116, 101, 114,
        44, 0, 32, 32, 32, 32, 95, 95, 117, 54, 52, 32, 117, 115, 101, 114, 95, 112, 116, 114, 32,
        61, 32, 40, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 41, 117, 115,
        101, 114, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 109, 97, 112, 95, 117, 112, 100, 97,
        116, 101, 95, 101, 108, 101, 109, 40, 38, 117, 115, 101, 114, 95, 112, 116, 114, 115, 44,
        32, 38, 112, 105, 100, 44, 32, 38, 117, 115, 101, 114, 95, 112, 116, 114, 44, 32, 66, 80,
        70, 95, 65, 78, 89, 41, 59, 0, 105, 110, 116, 32, 66, 80, 70, 95, 85, 82, 69, 84, 80, 82,
        79, 66, 69, 40, 112, 97, 109, 95, 103, 101, 116, 95, 117, 115, 101, 114, 95, 101, 120, 105,
        116, 41, 0, 32, 32, 32, 32, 95, 95, 117, 54, 52, 32, 42, 115, 116, 111, 114, 101, 100, 32,
        61, 32, 98, 112, 102, 95, 109, 97, 112, 95, 108, 111, 111, 107, 117, 112, 95, 101, 108,
        101, 109, 40, 38, 117, 115, 101, 114, 95, 112, 116, 114, 115, 44, 32, 38, 112, 105, 100,
        41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 109, 97, 112, 95, 100, 101, 108, 101, 116,
        101, 95, 101, 108, 101, 109, 40, 38, 117, 115, 101, 114, 95, 112, 116, 114, 115, 44, 32,
        38, 112, 105, 100, 41, 59, 0, 32, 32, 32, 32, 95, 95, 117, 54, 52, 32, 117, 115, 101, 114,
        95, 97, 100, 100, 114, 32, 61, 32, 48, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114,
        111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101, 114, 40, 38, 117, 115, 101, 114,
        95, 97, 100, 100, 114, 44, 32, 115, 105, 122, 101, 111, 102, 40, 117, 115, 101, 114, 95,
        97, 100, 100, 114, 41, 44, 32, 40, 99, 111, 110, 115, 116, 32, 118, 111, 105, 100, 32, 42,
        41, 40, 42, 115, 116, 111, 114, 101, 100, 41, 41, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40,
        33, 117, 115, 101, 114, 95, 97, 100, 100, 114, 41, 0, 32, 32, 32, 32, 98, 112, 102, 95,
        112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101, 114, 40, 101, 118, 116,
        45, 62, 117, 115, 101, 114, 110, 97, 109, 101, 44, 32, 115, 105, 122, 101, 111, 102, 40,
        101, 118, 116, 45, 62, 117, 115, 101, 114, 110, 97, 109, 101, 41, 44, 32, 40, 99, 111, 110,
        115, 116, 32, 118, 111, 105, 100, 32, 42, 41, 117, 115, 101, 114, 95, 97, 100, 100, 114,
        41, 59, 0, 48, 58, 49, 50, 0, 48, 58, 49, 48, 0, 48, 58, 49, 51, 0, 108, 105, 99, 101, 110,
        115, 101, 0, 46, 98, 115, 115, 0, 46, 109, 97, 112, 115, 0, 117, 112, 114, 111, 98, 101,
        47, 47, 108, 105, 98, 47, 120, 56, 54, 95, 54, 52, 45, 108, 105, 110, 117, 120, 45, 103,
        110, 117, 47, 108, 105, 98, 112, 97, 109, 46, 115, 111, 46, 48, 58, 112, 97, 109, 95, 103,
        101, 116, 95, 97, 117, 116, 104, 116, 111, 107, 0, 117, 114, 101, 116, 112, 114, 111, 98,
        101, 47, 47, 108, 105, 98, 47, 120, 56, 54, 95, 54, 52, 45, 108, 105, 110, 117, 120, 45,
        103, 110, 117, 47, 108, 105, 98, 112, 97, 109, 46, 115, 111, 46, 48, 58, 112, 97, 109, 95,
        103, 101, 116, 95, 97, 117, 116, 104, 116, 111, 107, 0, 117, 112, 114, 111, 98, 101, 47,
        47, 108, 105, 98, 47, 120, 56, 54, 95, 54, 52, 45, 108, 105, 110, 117, 120, 45, 103, 110,
        117, 47, 108, 105, 98, 112, 97, 109, 46, 115, 111, 46, 48, 58, 112, 97, 109, 95, 103, 101,
        116, 95, 117, 115, 101, 114, 0, 117, 114, 101, 116, 112, 114, 111, 98, 101, 47, 47, 108,
        105, 98, 47, 120, 56, 54, 95, 54, 52, 45, 108, 105, 110, 117, 120, 45, 103, 110, 117, 47,
        108, 105, 98, 112, 97, 109, 46, 115, 111, 46, 48, 58, 112, 97, 109, 95, 103, 101, 116, 95,
        117, 115, 101, 114, 0, 0, 0, 0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 68, 0, 0, 0,
        68, 0, 0, 0, 36, 4, 0, 0, 104, 4, 0, 0, 100, 0, 0, 0, 8, 0, 0, 0, 155, 7, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 34, 0, 0, 0, 212, 7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 16, 8, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 36, 0, 0, 0, 70, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 37, 0, 0, 0, 16, 0,
        0, 0, 155, 7, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 214, 1, 0, 0, 37, 2, 0, 0, 5, 168, 0, 0, 8, 0,
        0, 0, 214, 1, 0, 0, 76, 2, 0, 0, 14, 188, 0, 0, 16, 0, 0, 0, 214, 1, 0, 0, 76, 2, 0, 0, 41,
        188, 0, 0, 24, 0, 0, 0, 214, 1, 0, 0, 76, 2, 0, 0, 8, 188, 0, 0, 32, 0, 0, 0, 214, 1, 0, 0,
        123, 2, 0, 0, 8, 192, 0, 0, 72, 0, 0, 0, 214, 1, 0, 0, 165, 2, 0, 0, 2, 196, 0, 0, 104, 0,
        0, 0, 214, 1, 0, 0, 37, 2, 0, 0, 5, 168, 0, 0, 212, 7, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 214,
        1, 0, 0, 228, 2, 0, 0, 0, 216, 0, 0, 8, 0, 0, 0, 214, 1, 0, 0, 12, 3, 0, 0, 17, 224, 0, 0,
        16, 0, 0, 0, 214, 1, 0, 0, 12, 3, 0, 0, 44, 224, 0, 0, 24, 0, 0, 0, 214, 1, 0, 0, 12, 3, 0,
        0, 11, 224, 0, 0, 32, 0, 0, 0, 214, 1, 0, 0, 62, 3, 0, 0, 15, 228, 0, 0, 56, 0, 0, 0, 214,
        1, 0, 0, 93, 3, 0, 0, 21, 236, 0, 0, 88, 0, 0, 0, 214, 1, 0, 0, 155, 3, 0, 0, 9, 240, 0, 0,
        128, 0, 0, 0, 214, 1, 0, 0, 172, 3, 0, 0, 5, 248, 0, 0, 152, 0, 0, 0, 214, 1, 0, 0, 218, 3,
        0, 0, 13, 252, 0, 0, 168, 0, 0, 0, 214, 1, 0, 0, 236, 3, 0, 0, 11, 8, 1, 0, 176, 0, 0, 0,
        214, 1, 0, 0, 5, 4, 0, 0, 71, 12, 1, 0, 200, 0, 0, 0, 214, 1, 0, 0, 5, 4, 0, 0, 5, 12, 1,
        0, 216, 0, 0, 0, 214, 1, 0, 0, 86, 4, 0, 0, 10, 16, 1, 0, 224, 0, 0, 0, 214, 1, 0, 0, 86,
        4, 0, 0, 9, 16, 1, 0, 232, 0, 0, 0, 214, 1, 0, 0, 106, 4, 0, 0, 25, 28, 1, 0, 16, 1, 0, 0,
        214, 1, 0, 0, 185, 4, 0, 0, 9, 32, 1, 0, 24, 1, 0, 0, 214, 1, 0, 0, 199, 4, 0, 0, 16, 40,
        1, 0, 32, 1, 0, 0, 214, 1, 0, 0, 199, 4, 0, 0, 14, 40, 1, 0, 40, 1, 0, 0, 214, 1, 0, 0,
        219, 4, 0, 0, 32, 44, 1, 0, 56, 1, 0, 0, 214, 1, 0, 0, 219, 4, 0, 0, 5, 44, 1, 0, 80, 1, 0,
        0, 214, 1, 0, 0, 20, 5, 0, 0, 77, 48, 1, 0, 88, 1, 0, 0, 214, 1, 0, 0, 20, 5, 0, 0, 30, 48,
        1, 0, 104, 1, 0, 0, 214, 1, 0, 0, 20, 5, 0, 0, 5, 48, 1, 0, 120, 1, 0, 0, 214, 1, 0, 0,
        108, 5, 0, 0, 5, 52, 1, 0, 144, 1, 0, 0, 214, 1, 0, 0, 228, 2, 0, 0, 5, 216, 0, 0, 16, 8,
        0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 214, 1, 0, 0, 140, 5, 0, 0, 5, 72, 1, 0, 8, 0, 0, 0, 214, 1,
        0, 0, 12, 3, 0, 0, 17, 92, 1, 0, 16, 0, 0, 0, 214, 1, 0, 0, 12, 3, 0, 0, 44, 92, 1, 0, 24,
        0, 0, 0, 214, 1, 0, 0, 12, 3, 0, 0, 11, 92, 1, 0, 32, 0, 0, 0, 214, 1, 0, 0, 175, 5, 0, 0,
        11, 96, 1, 0, 72, 0, 0, 0, 214, 1, 0, 0, 217, 5, 0, 0, 5, 100, 1, 0, 104, 0, 0, 0, 214, 1,
        0, 0, 140, 5, 0, 0, 5, 72, 1, 0, 70, 8, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 214, 1, 0, 0, 24, 6,
        0, 0, 0, 120, 1, 0, 8, 0, 0, 0, 214, 1, 0, 0, 12, 3, 0, 0, 17, 128, 1, 0, 16, 0, 0, 0, 214,
        1, 0, 0, 12, 3, 0, 0, 44, 128, 1, 0, 24, 0, 0, 0, 214, 1, 0, 0, 12, 3, 0, 0, 11, 128, 1, 0,
        32, 0, 0, 0, 214, 1, 0, 0, 62, 3, 0, 0, 15, 132, 1, 0, 56, 0, 0, 0, 214, 1, 0, 0, 61, 6, 0,
        0, 21, 140, 1, 0, 88, 0, 0, 0, 214, 1, 0, 0, 155, 3, 0, 0, 9, 144, 1, 0, 128, 0, 0, 0, 214,
        1, 0, 0, 120, 6, 0, 0, 5, 152, 1, 0, 152, 0, 0, 0, 214, 1, 0, 0, 218, 3, 0, 0, 13, 156, 1,
        0, 168, 0, 0, 0, 214, 1, 0, 0, 163, 6, 0, 0, 11, 168, 1, 0, 176, 0, 0, 0, 214, 1, 0, 0,
        188, 6, 0, 0, 71, 172, 1, 0, 200, 0, 0, 0, 214, 1, 0, 0, 188, 6, 0, 0, 5, 172, 1, 0, 216,
        0, 0, 0, 214, 1, 0, 0, 13, 7, 0, 0, 10, 176, 1, 0, 224, 0, 0, 0, 214, 1, 0, 0, 13, 7, 0, 0,
        9, 176, 1, 0, 232, 0, 0, 0, 214, 1, 0, 0, 106, 4, 0, 0, 25, 188, 1, 0, 16, 1, 0, 0, 214, 1,
        0, 0, 185, 4, 0, 0, 9, 192, 1, 0, 24, 1, 0, 0, 214, 1, 0, 0, 199, 4, 0, 0, 16, 200, 1, 0,
        32, 1, 0, 0, 214, 1, 0, 0, 199, 4, 0, 0, 14, 200, 1, 0, 40, 1, 0, 0, 214, 1, 0, 0, 219, 4,
        0, 0, 32, 204, 1, 0, 56, 1, 0, 0, 214, 1, 0, 0, 219, 4, 0, 0, 5, 204, 1, 0, 80, 1, 0, 0,
        214, 1, 0, 0, 33, 7, 0, 0, 77, 208, 1, 0, 88, 1, 0, 0, 214, 1, 0, 0, 33, 7, 0, 0, 30, 208,
        1, 0, 104, 1, 0, 0, 214, 1, 0, 0, 33, 7, 0, 0, 5, 208, 1, 0, 120, 1, 0, 0, 214, 1, 0, 0,
        108, 5, 0, 0, 5, 212, 1, 0, 144, 1, 0, 0, 214, 1, 0, 0, 24, 6, 0, 0, 5, 120, 1, 0, 16, 0,
        0, 0, 155, 7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 121, 7, 0, 0, 0, 0, 0, 0, 212, 7,
        0, 0, 1, 0, 0, 0, 32, 0, 0, 0, 23, 0, 0, 0, 126, 7, 0, 0, 0, 0, 0, 0, 16, 8, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 23, 0, 0, 0, 131, 7, 0, 0, 0, 0, 0, 0, 70, 8, 0, 0, 1, 0, 0, 0, 32, 0, 0, 0,
        23, 0, 0, 0, 126, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 149, 2, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0,
        2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 216, 2, 0, 0, 0, 0, 0, 0, 104,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0,
        0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 4, 0, 0, 0,
        0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 74, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        184, 4, 0, 0, 0, 0, 0, 0, 160, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 134, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 88, 6, 0, 0, 0, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 188, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 6, 0, 0, 0, 0, 0, 0, 160, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 245, 0, 0, 0, 1, 0, 0, 0, 3,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 8, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 253, 0, 0, 0, 8,
        0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 116, 8, 0, 0, 0, 0, 0, 0, 212, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 1, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 8, 0, 0, 0, 0,
        0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 147, 1, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200,
        8, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0,
        0, 16, 0, 0, 0, 0, 0, 0, 0, 208, 1, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 216, 8, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 8,
        0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 16, 2, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 9, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
        5, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 74, 2, 0, 0, 9, 0, 0, 0, 64,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 9, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0,
        0, 2, 0, 0, 0, 6, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 135, 2, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 9, 0, 0, 0, 0, 0, 0, 3, 14,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        140, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 23, 0, 0, 0,
        0, 0, 0, 236, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0,
    ];
}
