// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder.name("icmp_bpf").prog("icmp_filter_prog");
        builder.build()
    }
    pub struct OpenIcmpMaps<'obj> {
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenIcmpMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct IcmpMaps<'obj> {
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> IcmpMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenIcmpProgs<'obj> {
        pub icmp_filter_prog: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenIcmpProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut icmp_filter_prog = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "icmp_filter_prog" => icmp_filter_prog = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                icmp_filter_prog: icmp_filter_prog.expect("prog `icmp_filter_prog` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct IcmpProgs<'obj> {
        pub icmp_filter_prog: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> IcmpProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenIcmpProgs<'obj>) -> Self {
            Self {
                icmp_filter_prog: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.icmp_filter_prog.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct IcmpSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> IcmpSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenIcmpSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenIcmpSkel {
                maps: unsafe { OpenIcmpMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenIcmpProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for IcmpSkelBuilder {
        type Output = OpenIcmpSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenIcmpSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenIcmpSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __sk_buff {
            pub len: u32,
            pub pkt_type: u32,
            pub mark: u32,
            pub queue_mapping: u32,
            pub protocol: u32,
            pub vlan_present: u32,
            pub vlan_tci: u32,
            pub vlan_proto: u32,
            pub priority: u32,
            pub ingress_ifindex: u32,
            pub ifindex: u32,
            pub tc_index: u32,
            pub cb: [u32; 5],
            pub hash: u32,
            pub tc_classid: u32,
            pub data: u32,
            pub data_end: u32,
            pub napi_id: u32,
            pub family: u32,
            pub remote_ip4: u32,
            pub local_ip4: u32,
            pub remote_ip6: [u32; 4],
            pub local_ip6: [u32; 4],
            pub remote_port: u32,
            pub local_port: u32,
            pub data_meta: u32,
            pub __anon___sk_buff_1: __anon___sk_buff_1,
            pub tstamp: u64,
            pub wire_len: u32,
            pub gso_segs: u32,
            pub __anon___sk_buff_2: __anon___sk_buff_2,
            pub gso_size: u32,
            pub tstamp_type: u8,
            pub hwtstamp: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon___sk_buff_1 {
            pub flow_keys: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon___sk_buff_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon___sk_buff_1 {
            fn default() -> Self {
                Self {
                    flow_keys: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon___sk_buff_2 {
            pub sk: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon___sk_buff_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon___sk_buff_2 {
            fn default() -> Self {
                Self {
                    sk: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub _license: [i8; 4],
        }
    }
    pub struct OpenIcmpSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenIcmpMaps<'obj>,
        pub progs: OpenIcmpProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenIcmpSkel<'obj> {
        type Output = IcmpSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<IcmpSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(IcmpSkel {
                maps: unsafe { IcmpMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: IcmpProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: IcmpLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct IcmpLinks {
        pub icmp_filter_prog: Option<libbpf_rs::Link>,
    }
    pub struct IcmpSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: IcmpMaps<'obj>,
        pub progs: IcmpProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: IcmpLinks,
    }

    unsafe impl Send for IcmpSkel<'_> {}
    unsafe impl Sync for IcmpSkel<'_> {}

    impl<'obj> Skel<'obj> for IcmpSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = IcmpLinks {
                icmp_filter_prog: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl IcmpSkel<'_> {}
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 232, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 7, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98,
        0, 115, 111, 99, 107, 101, 116, 0, 108, 105, 99, 101, 110, 115, 101, 0, 105, 99, 109, 112,
        46, 98, 112, 102, 46, 99, 0, 76, 66, 66, 48, 95, 57, 0, 105, 99, 109, 112, 95, 102, 105,
        108, 116, 101, 114, 95, 112, 114, 111, 103, 0, 95, 108, 105, 99, 101, 110, 115, 101, 0, 46,
        66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 43, 0, 0, 0, 0, 0, 3, 0, 120, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 50, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 1, 0, 0, 0, 0, 0, 0, 67, 0, 0, 0,
        17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 191, 23, 0, 0, 0, 0, 0, 0,
        183, 6, 0, 0, 0, 0, 0, 0, 107, 106, 254, 255, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3,
        0, 0, 254, 255, 255, 255, 183, 2, 0, 0, 12, 0, 0, 0, 183, 4, 0, 0, 2, 0, 0, 0, 133, 0, 0,
        0, 26, 0, 0, 0, 109, 6, 38, 0, 0, 0, 0, 0, 105, 161, 254, 255, 0, 0, 0, 0, 191, 18, 0, 0,
        0, 0, 0, 0, 220, 2, 0, 0, 16, 0, 0, 0, 107, 42, 254, 255, 0, 0, 0, 0, 85, 1, 33, 0, 8, 0,
        0, 0, 115, 106, 253, 255, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 253, 255,
        255, 255, 191, 113, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 14, 0, 0, 0, 183, 4, 0, 0, 1, 0, 0, 0,
        133, 0, 0, 0, 26, 0, 0, 0, 109, 6, 25, 0, 0, 0, 0, 0, 113, 161, 253, 255, 0, 0, 0, 0, 119,
        1, 0, 0, 4, 0, 0, 0, 115, 26, 253, 255, 0, 0, 0, 0, 85, 1, 21, 0, 4, 0, 0, 0, 115, 106,
        252, 255, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 252, 255, 255, 255, 191, 113,
        0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 23, 0, 0, 0, 183, 4, 0, 0, 1, 0, 0, 0, 133, 0, 0, 0, 26, 0,
        0, 0, 109, 6, 13, 0, 0, 0, 0, 0, 113, 161, 252, 255, 0, 0, 0, 0, 85, 1, 11, 0, 1, 0, 0, 0,
        115, 106, 251, 255, 0, 0, 0, 0, 191, 163, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 251, 255, 255, 255,
        191, 113, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 34, 0, 0, 0, 183, 4, 0, 0, 1, 0, 0, 0, 133, 0, 0,
        0, 26, 0, 0, 0, 109, 6, 3, 0, 0, 0, 0, 0, 113, 161, 251, 255, 0, 0, 0, 0, 85, 1, 1, 0, 8,
        0, 0, 0, 97, 118, 0, 0, 0, 0, 0, 0, 191, 96, 0, 0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0,
        71, 80, 76, 0, 0, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 36, 3, 0, 0, 36, 3, 0,
        0, 42, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 34, 0, 0, 4, 192, 0, 0, 0,
        11, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 24, 0, 0, 0, 3,
        0, 0, 0, 64, 0, 0, 0, 29, 0, 0, 0, 3, 0, 0, 0, 96, 0, 0, 0, 43, 0, 0, 0, 3, 0, 0, 0, 128,
        0, 0, 0, 52, 0, 0, 0, 3, 0, 0, 0, 160, 0, 0, 0, 65, 0, 0, 0, 3, 0, 0, 0, 192, 0, 0, 0, 74,
        0, 0, 0, 3, 0, 0, 0, 224, 0, 0, 0, 85, 0, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 94, 0, 0, 0, 3, 0,
        0, 0, 32, 1, 0, 0, 110, 0, 0, 0, 3, 0, 0, 0, 64, 1, 0, 0, 118, 0, 0, 0, 3, 0, 0, 0, 96, 1,
        0, 0, 127, 0, 0, 0, 5, 0, 0, 0, 128, 1, 0, 0, 130, 0, 0, 0, 3, 0, 0, 0, 32, 2, 0, 0, 135,
        0, 0, 0, 3, 0, 0, 0, 64, 2, 0, 0, 146, 0, 0, 0, 3, 0, 0, 0, 96, 2, 0, 0, 151, 0, 0, 0, 3,
        0, 0, 0, 128, 2, 0, 0, 160, 0, 0, 0, 3, 0, 0, 0, 160, 2, 0, 0, 168, 0, 0, 0, 3, 0, 0, 0,
        192, 2, 0, 0, 175, 0, 0, 0, 3, 0, 0, 0, 224, 2, 0, 0, 186, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0,
        196, 0, 0, 0, 7, 0, 0, 0, 32, 3, 0, 0, 207, 0, 0, 0, 7, 0, 0, 0, 160, 3, 0, 0, 217, 0, 0,
        0, 3, 0, 0, 0, 32, 4, 0, 0, 229, 0, 0, 0, 3, 0, 0, 0, 64, 4, 0, 0, 240, 0, 0, 0, 3, 0, 0,
        0, 96, 4, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 128, 4, 0, 0, 250, 0, 0, 0, 10, 0, 0, 0, 192, 4, 0,
        0, 1, 1, 0, 0, 3, 0, 0, 0, 0, 5, 0, 0, 10, 1, 0, 0, 3, 0, 0, 0, 32, 5, 0, 0, 0, 0, 0, 0,
        12, 0, 0, 0, 64, 5, 0, 0, 19, 1, 0, 0, 3, 0, 0, 0, 128, 5, 0, 0, 28, 1, 0, 0, 14, 0, 0, 0,
        160, 5, 0, 0, 40, 1, 0, 0, 10, 0, 0, 0, 192, 5, 0, 0, 49, 1, 0, 0, 0, 0, 0, 8, 4, 0, 0, 0,
        55, 1, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0,
        0, 0, 6, 0, 0, 0, 5, 0, 0, 0, 68, 1, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 6, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 8, 0,
        0, 0, 88, 1, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 22, 0, 0, 0, 98, 1, 0,
        0, 0, 0, 0, 8, 11, 0, 0, 0, 104, 1, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 5, 8, 0, 0, 0, 123, 1, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 23,
        0, 0, 0, 126, 1, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 131, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 17, 0, 0, 0, 145, 1, 0, 0, 1, 0, 0, 0, 149, 1, 0, 0, 0, 0,
        0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 153, 1, 0, 0, 1, 0, 0, 12, 16, 0, 0, 0, 170, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 19, 0, 0, 0, 6, 0, 0, 0,
        4, 0, 0, 0, 175, 1, 0, 0, 0, 0, 0, 14, 20, 0, 0, 0, 1, 0, 0, 0, 184, 1, 0, 0, 0, 0, 0, 7,
        0, 0, 0, 0, 198, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 27, 4, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 21,
        0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 95, 95, 115, 107, 95, 98, 117, 102, 102, 0, 108, 101,
        110, 0, 112, 107, 116, 95, 116, 121, 112, 101, 0, 109, 97, 114, 107, 0, 113, 117, 101, 117,
        101, 95, 109, 97, 112, 112, 105, 110, 103, 0, 112, 114, 111, 116, 111, 99, 111, 108, 0,
        118, 108, 97, 110, 95, 112, 114, 101, 115, 101, 110, 116, 0, 118, 108, 97, 110, 95, 116,
        99, 105, 0, 118, 108, 97, 110, 95, 112, 114, 111, 116, 111, 0, 112, 114, 105, 111, 114,
        105, 116, 121, 0, 105, 110, 103, 114, 101, 115, 115, 95, 105, 102, 105, 110, 100, 101, 120,
        0, 105, 102, 105, 110, 100, 101, 120, 0, 116, 99, 95, 105, 110, 100, 101, 120, 0, 99, 98,
        0, 104, 97, 115, 104, 0, 116, 99, 95, 99, 108, 97, 115, 115, 105, 100, 0, 100, 97, 116, 97,
        0, 100, 97, 116, 97, 95, 101, 110, 100, 0, 110, 97, 112, 105, 95, 105, 100, 0, 102, 97,
        109, 105, 108, 121, 0, 114, 101, 109, 111, 116, 101, 95, 105, 112, 52, 0, 108, 111, 99, 97,
        108, 95, 105, 112, 52, 0, 114, 101, 109, 111, 116, 101, 95, 105, 112, 54, 0, 108, 111, 99,
        97, 108, 95, 105, 112, 54, 0, 114, 101, 109, 111, 116, 101, 95, 112, 111, 114, 116, 0, 108,
        111, 99, 97, 108, 95, 112, 111, 114, 116, 0, 100, 97, 116, 97, 95, 109, 101, 116, 97, 0,
        116, 115, 116, 97, 109, 112, 0, 119, 105, 114, 101, 95, 108, 101, 110, 0, 103, 115, 111,
        95, 115, 101, 103, 115, 0, 103, 115, 111, 95, 115, 105, 122, 101, 0, 116, 115, 116, 97,
        109, 112, 95, 116, 121, 112, 101, 0, 104, 119, 116, 115, 116, 97, 109, 112, 0, 95, 95, 117,
        51, 50, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 95, 95, 65, 82,
        82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 102, 108, 111, 119, 95, 107,
        101, 121, 115, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108,
        111, 110, 103, 32, 108, 111, 110, 103, 0, 115, 107, 0, 95, 95, 117, 56, 0, 117, 110, 115,
        105, 103, 110, 101, 100, 32, 99, 104, 97, 114, 0, 115, 107, 98, 0, 105, 110, 116, 0, 105,
        99, 109, 112, 95, 102, 105, 108, 116, 101, 114, 95, 112, 114, 111, 103, 0, 99, 104, 97,
        114, 0, 95, 108, 105, 99, 101, 110, 115, 101, 0, 98, 112, 102, 95, 102, 108, 111, 119, 95,
        107, 101, 121, 115, 0, 98, 112, 102, 95, 115, 111, 99, 107, 0, 47, 104, 111, 109, 101, 47,
        112, 104, 105, 110, 103, 117, 121, 101, 110, 100, 112, 47, 87, 83, 45, 108, 105, 110, 117,
        120, 47, 101, 98, 112, 102, 47, 101, 101, 45, 101, 98, 112, 102, 47, 99, 104, 52, 95, 101,
        110, 101, 116, 119, 111, 114, 107, 47, 105, 99, 109, 112, 95, 102, 105, 108, 116, 101, 114,
        47, 115, 114, 99, 47, 98, 112, 102, 47, 105, 99, 109, 112, 46, 98, 112, 102, 46, 99, 0,
        105, 110, 116, 32, 105, 99, 109, 112, 95, 102, 105, 108, 116, 101, 114, 95, 112, 114, 111,
        103, 40, 115, 116, 114, 117, 99, 116, 32, 95, 95, 115, 107, 95, 98, 117, 102, 102, 32, 42,
        115, 107, 98, 41, 0, 9, 95, 95, 117, 49, 54, 32, 101, 116, 104, 95, 112, 114, 111, 116,
        111, 32, 61, 32, 48, 59, 0, 9, 105, 102, 32, 40, 98, 112, 102, 95, 115, 107, 98, 95, 108,
        111, 97, 100, 95, 98, 121, 116, 101, 115, 40, 115, 107, 98, 44, 32, 69, 84, 72, 95, 84, 89,
        80, 69, 44, 32, 38, 101, 116, 104, 95, 112, 114, 111, 116, 111, 44, 0, 9, 101, 116, 104,
        95, 112, 114, 111, 116, 111, 32, 61, 32, 98, 112, 102, 95, 110, 116, 111, 104, 115, 40,
        101, 116, 104, 95, 112, 114, 111, 116, 111, 41, 59, 0, 9, 105, 102, 32, 40, 101, 116, 104,
        95, 112, 114, 111, 116, 111, 32, 33, 61, 32, 69, 84, 72, 95, 80, 95, 73, 80, 41, 32, 123,
        0, 9, 95, 95, 117, 56, 32, 105, 112, 95, 118, 101, 114, 115, 105, 111, 110, 32, 61, 32, 48,
        59, 0, 9, 105, 102, 32, 40, 98, 112, 102, 95, 115, 107, 98, 95, 108, 111, 97, 100, 95, 98,
        121, 116, 101, 115, 40, 115, 107, 98, 44, 32, 69, 84, 72, 95, 72, 76, 69, 78, 44, 38, 105,
        112, 95, 118, 101, 114, 115, 105, 111, 110, 44, 0, 9, 105, 112, 95, 118, 101, 114, 115,
        105, 111, 110, 32, 61, 32, 105, 112, 95, 118, 101, 114, 115, 105, 111, 110, 32, 62, 62, 32,
        52, 59, 0, 9, 105, 102, 32, 40, 105, 112, 95, 118, 101, 114, 115, 105, 111, 110, 32, 33,
        61, 32, 52, 41, 32, 123, 0, 9, 95, 95, 117, 56, 32, 105, 112, 95, 112, 114, 111, 116, 111,
        32, 61, 32, 48, 59, 0, 9, 105, 102, 32, 40, 98, 112, 102, 95, 115, 107, 98, 95, 108, 111,
        97, 100, 95, 98, 121, 116, 101, 115, 40, 115, 107, 98, 44, 32, 69, 84, 72, 95, 72, 76, 69,
        78, 32, 43, 32, 57, 44, 32, 38, 105, 112, 95, 112, 114, 111, 116, 111, 44, 0, 9, 95, 95,
        117, 56, 32, 105, 99, 109, 112, 95, 116, 121, 112, 101, 32, 61, 32, 48, 59, 0, 9, 105, 102,
        32, 40, 98, 112, 102, 95, 115, 107, 98, 95, 108, 111, 97, 100, 95, 98, 121, 116, 101, 115,
        40, 115, 107, 98, 44, 32, 73, 67, 77, 80, 95, 76, 69, 78, 44, 32, 38, 105, 99, 109, 112,
        95, 116, 121, 112, 101, 44, 32, 115, 105, 122, 101, 111, 102, 40, 105, 99, 109, 112, 95,
        116, 121, 112, 101, 41, 41, 32, 60, 32, 48, 41, 0, 9, 114, 101, 116, 117, 114, 110, 32,
        115, 107, 98, 45, 62, 108, 101, 110, 59, 0, 125, 0, 48, 58, 48, 0, 108, 105, 99, 101, 110,
        115, 101, 0, 115, 111, 99, 107, 101, 116, 0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        20, 0, 0, 0, 20, 0, 0, 0, 108, 1, 0, 0, 128, 1, 0, 0, 28, 0, 0, 0, 8, 0, 0, 0, 35, 4, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 16, 0, 0, 0, 35, 4, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0,
        207, 1, 0, 0, 35, 2, 0, 0, 0, 56, 0, 0, 16, 0, 0, 0, 207, 1, 0, 0, 79, 2, 0, 0, 8, 64, 0,
        0, 32, 0, 0, 0, 207, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 207, 1, 0, 0, 101, 2, 0,
        0, 6, 72, 0, 0, 64, 0, 0, 0, 207, 1, 0, 0, 101, 2, 0, 0, 6, 72, 0, 0, 72, 0, 0, 0, 207, 1,
        0, 0, 152, 2, 0, 0, 14, 88, 0, 0, 96, 0, 0, 0, 207, 1, 0, 0, 152, 2, 0, 0, 12, 88, 0, 0,
        104, 0, 0, 0, 207, 1, 0, 0, 187, 2, 0, 0, 6, 92, 0, 0, 112, 0, 0, 0, 207, 1, 0, 0, 217, 2,
        0, 0, 7, 108, 0, 0, 136, 0, 0, 0, 207, 1, 0, 0, 239, 2, 0, 0, 6, 112, 0, 0, 168, 0, 0, 0,
        207, 1, 0, 0, 239, 2, 0, 0, 6, 112, 0, 0, 176, 0, 0, 0, 207, 1, 0, 0, 34, 3, 0, 0, 15, 128,
        0, 0, 192, 0, 0, 0, 207, 1, 0, 0, 34, 3, 0, 0, 13, 128, 0, 0, 200, 0, 0, 0, 207, 1, 0, 0,
        65, 3, 0, 0, 6, 132, 0, 0, 208, 0, 0, 0, 207, 1, 0, 0, 89, 3, 0, 0, 7, 148, 0, 0, 232, 0,
        0, 0, 207, 1, 0, 0, 109, 3, 0, 0, 6, 152, 0, 0, 8, 1, 0, 0, 207, 1, 0, 0, 109, 3, 0, 0, 6,
        152, 0, 0, 32, 1, 0, 0, 207, 1, 0, 0, 163, 3, 0, 0, 7, 180, 0, 0, 56, 1, 0, 0, 207, 1, 0,
        0, 184, 3, 0, 0, 6, 184, 0, 0, 88, 1, 0, 0, 207, 1, 0, 0, 184, 3, 0, 0, 6, 184, 0, 0, 112,
        1, 0, 0, 207, 1, 0, 0, 3, 4, 0, 0, 14, 212, 0, 0, 120, 1, 0, 0, 207, 1, 0, 0, 21, 4, 0, 0,
        1, 216, 0, 0, 16, 0, 0, 0, 35, 4, 0, 0, 1, 0, 0, 0, 112, 1, 0, 0, 2, 0, 0, 0, 23, 4, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 0, 0, 0, 0, 0, 0, 0, 144, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 0, 136, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0,
        1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 184, 2, 0, 0, 0, 0, 0, 0, 4, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        76, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 2, 0, 0, 0,
        0, 0, 0, 102, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 81, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40,
        10, 0, 0, 0, 0, 0, 0, 188, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
