// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("ksyscall_execve_bpf")
            .map("rb", false)
            .map("ksyscall.bss", true)
            .map("ksyscal.kconfig", true)
            .prog("kprobe_sys_execve");
        builder.build()
    }
    pub struct OpenKsyscallExecveMaps<'obj> {
        pub rb: libbpf_rs::OpenMapMut<'obj>,
        pub bss: libbpf_rs::OpenMapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        pub kconfig: libbpf_rs::OpenMapMut<'obj>,
        pub kconfig_data: Option<&'obj mut types::kconfig>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenKsyscallExecveMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut rb = None;
            let mut bss = None;
            let mut kconfig = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "rb" => rb = Some(map),
                    "ksyscall.bss" => bss = Some(map),
                    "ksyscal.kconfig" => kconfig = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                rb: rb.expect("map `rb` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(1)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                kconfig: kconfig.expect("map `kconfig` not present"),
                kconfig_data: unsafe {
                    config
                        .map_mmap_ptr(2)
                        .expect("BPF map `kconfig` does not have mmap pointer")
                        .cast::<types::kconfig>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct KsyscallExecveMaps<'obj> {
        pub rb: libbpf_rs::MapMut<'obj>,
        pub bss: libbpf_rs::MapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        pub kconfig: libbpf_rs::MapMut<'obj>,
        pub kconfig_data: Option<&'obj types::kconfig>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> KsyscallExecveMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut rb = None;
            let mut bss = None;
            let mut kconfig = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "rb" => rb = Some(map),
                    "ksyscall.bss" => bss = Some(map),
                    "ksyscal.kconfig" => kconfig = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                rb: rb.expect("map `rb` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(1)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                kconfig: kconfig.expect("map `kconfig` not present"),
                kconfig_data: unsafe {
                    config
                        .map_mmap_ptr(2)
                        .expect("BPF map `kconfig` does not have mmap pointer")
                        .cast::<types::kconfig>()
                        .as_ref()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenKsyscallExecveProgs<'obj> {
        pub kprobe_sys_execve: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenKsyscallExecveProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut kprobe_sys_execve = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "kprobe_sys_execve" => kprobe_sys_execve = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                kprobe_sys_execve: kprobe_sys_execve.expect("prog `kprobe_sys_execve` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct KsyscallExecveProgs<'obj> {
        pub kprobe_sys_execve: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> KsyscallExecveProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenKsyscallExecveProgs<'obj>) -> Self {
            Self {
                kprobe_sys_execve: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.kprobe_sys_execve.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct KsyscallExecveSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> KsyscallExecveSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenKsyscallExecveSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenKsyscallExecveSkel {
                maps: unsafe { OpenKsyscallExecveMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenKsyscallExecveProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for KsyscallExecveSkelBuilder {
        type Output = OpenKsyscallExecveSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenKsyscallExecveSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenKsyscallExecveSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 27],
            pub max_entries: *mut [i32; 65536],
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs {
            pub __anon_pt_regs_1: __anon_pt_regs_1,
            pub orig_x0: u64,
            pub syscallno: i32,
            pub unused2: u32,
            pub sdei_ttbr1: u64,
            pub pmr_save: u64,
            pub stackframe: [u64; 2],
            pub lockdep_hardirqs: u64,
            pub exit_rcu: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_pt_regs_1 {
            pub user_regs: user_pt_regs,
            pub __anon_pt_regs_3: __anon_pt_regs_3,
        }
        impl std::fmt::Debug for __anon_pt_regs_1 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_pt_regs_1 {
            fn default() -> Self {
                Self {
                    user_regs: user_pt_regs::default(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct user_pt_regs {
            pub regs: [u64; 31],
            pub sp: u64,
            pub pc: u64,
            pub pstate: u64,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_pt_regs_3 {
            pub regs: [u64; 31],
            pub sp: u64,
            pub pc: u64,
            pub pstate: u64,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct pt_regs___arm64 {
            pub orig_x0: u64,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct event {
            pub pid: u32,
            pub path: [i8; 128],
            pub argv: [[i8; 128]; 7],
        }
        impl Default for event {
            fn default() -> Self {
                Self {
                    pid: u32::default(),
                    path: [i8::default(); 128],
                    argv: [[i8::default(); 128]; 7],
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub dummy: event,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub rb: __anon_1,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct kconfig {
            pub LINUX_HAS_SYSCALL_WRAPPER: bool,
        }
    }
    pub struct OpenKsyscallExecveSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenKsyscallExecveMaps<'obj>,
        pub progs: OpenKsyscallExecveProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenKsyscallExecveSkel<'obj> {
        type Output = KsyscallExecveSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<KsyscallExecveSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(KsyscallExecveSkel {
                maps: unsafe { KsyscallExecveMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: KsyscallExecveProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: KsyscallExecveLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct KsyscallExecveLinks {
        pub kprobe_sys_execve: Option<libbpf_rs::Link>,
    }
    pub struct KsyscallExecveSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: KsyscallExecveMaps<'obj>,
        pub progs: KsyscallExecveProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: KsyscallExecveLinks,
    }

    unsafe impl Send for KsyscallExecveSkel<'_> {}
    unsafe impl Sync for KsyscallExecveSkel<'_> {}

    impl<'obj> Skel<'obj> for KsyscallExecveSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = KsyscallExecveLinks {
                kprobe_sys_execve: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl KsyscallExecveSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 10, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 107, 115, 121, 115, 99, 97, 108, 108, 47, 101, 120, 101, 99, 118, 101, 0, 46, 98,
        115, 115, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 109, 97, 112, 115, 0, 107, 115, 121,
        115, 99, 97, 108, 108, 95, 101, 120, 101, 99, 118, 101, 46, 98, 112, 102, 46, 99, 0, 76,
        66, 66, 48, 95, 49, 50, 0, 76, 66, 66, 48, 95, 49, 49, 0, 76, 66, 66, 48, 95, 49, 48, 0,
        76, 66, 66, 48, 95, 57, 0, 107, 112, 114, 111, 98, 101, 95, 115, 121, 115, 95, 101, 120,
        101, 99, 118, 101, 0, 76, 73, 78, 85, 88, 95, 72, 65, 83, 95, 83, 89, 83, 67, 65, 76, 76,
        95, 87, 82, 65, 80, 80, 69, 82, 0, 114, 98, 0, 100, 117, 109, 109, 121, 0, 76, 73, 67, 69,
        78, 83, 69, 0, 46, 114, 101, 108, 107, 115, 121, 115, 99, 97, 108, 108, 47, 101, 120, 101,
        99, 118, 101, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 74, 0, 0, 0, 0, 0, 3, 0, 40, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 82, 0, 0, 0, 0, 0, 3, 0, 24, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 90, 0, 0, 0,
        0, 0, 3, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 98, 0, 0, 0, 0, 0, 3, 0, 224,
        3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 105, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 120, 7, 0, 0, 0, 0, 0, 0, 123, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 149, 0, 0, 0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0,
        152, 0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0, 158, 0, 0, 0,
        17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 24, 2, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 113, 34, 0, 0, 0, 0, 0, 0, 21, 2, 129, 0, 0, 0, 0, 0, 121, 22, 0, 0, 0,
        0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 191, 99, 0, 0, 0, 0, 0, 0, 15, 19, 0, 0, 0, 0, 0, 0,
        191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133,
        0, 0, 0, 113, 0, 0, 0, 183, 1, 0, 0, 8, 0, 0, 0, 15, 22, 0, 0, 0, 0, 0, 0, 121, 168, 248,
        255, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0,
        8, 0, 0, 0, 191, 99, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 113, 0, 0, 0, 121, 167, 248, 255, 0,
        0, 0, 0, 183, 9, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2,
        0, 0, 4, 4, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0, 191, 6, 0, 0, 0, 0,
        0, 0, 21, 6, 102, 0, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 99,
        6, 0, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 4, 0, 0, 0, 183, 2, 0, 0, 128,
        0, 0, 0, 191, 131, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 154, 248, 255, 0, 0,
        0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0,
        191, 115, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 121, 163, 248, 255, 0, 0, 0, 0, 21,
        3, 83, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 132, 0, 0, 0, 183, 2, 0, 0,
        128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 183, 8, 0, 0, 0, 0, 0, 0, 123, 138, 248, 255, 0,
        0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 8, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7,
        1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 121,
        163, 248, 255, 0, 0, 0, 0, 21, 3, 69, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0,
        4, 1, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 138, 248, 255, 0,
        0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 16, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0,
        7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 121,
        163, 248, 255, 0, 0, 0, 0, 21, 3, 56, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0,
        132, 1, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 138, 248, 255,
        0, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 24, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0,
        0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0,
        121, 163, 248, 255, 0, 0, 0, 0, 21, 3, 43, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1,
        0, 0, 4, 2, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 138, 248,
        255, 0, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 32, 0, 0, 0, 191, 161, 0, 0, 0, 0,
        0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0,
        121, 163, 248, 255, 0, 0, 0, 0, 21, 3, 30, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1,
        0, 0, 132, 2, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 138, 248,
        255, 0, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 40, 0, 0, 0, 191, 161, 0, 0, 0, 0,
        0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0,
        121, 163, 248, 255, 0, 0, 0, 0, 21, 3, 17, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1,
        0, 0, 4, 3, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 138, 248,
        255, 0, 0, 0, 0, 7, 7, 0, 0, 48, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 248, 255,
        255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0,
        121, 163, 248, 255, 0, 0, 0, 0, 21, 3, 4, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1,
        0, 0, 132, 3, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 191, 97, 0, 0,
        0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0,
        149, 0, 0, 0, 0, 0, 0, 0, 121, 23, 8, 0, 0, 0, 0, 0, 121, 24, 0, 0, 0, 0, 0, 0, 183, 9, 0,
        0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 4, 4, 0, 0,
        183, 3, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0, 191, 6, 0, 0, 0, 0, 0, 0, 21, 6, 244,
        255, 0, 0, 0, 0, 133, 0, 0, 0, 14, 0, 0, 0, 119, 0, 0, 0, 32, 0, 0, 0, 99, 6, 0, 0, 0, 0,
        0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 4, 0, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 191,
        131, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 154, 248, 255, 0, 0, 0, 0, 191,
        161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 191, 115,
        0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 121, 163, 248, 255, 0, 0, 0, 0, 21, 3, 225,
        255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 132, 0, 0, 0, 183, 2, 0, 0, 128, 0,
        0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 183, 8, 0, 0, 0, 0, 0, 0, 123, 138, 248, 255, 0, 0, 0, 0,
        191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 8, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0,
        248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 121, 163, 248,
        255, 0, 0, 0, 0, 21, 3, 211, 255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 4, 1,
        0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 138, 248, 255, 0, 0, 0,
        0, 191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 16, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1,
        0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0, 121, 163,
        248, 255, 0, 0, 0, 0, 21, 3, 198, 255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0,
        132, 1, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 138, 248, 255,
        0, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 24, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0,
        0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0,
        121, 163, 248, 255, 0, 0, 0, 0, 21, 3, 185, 255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7,
        1, 0, 0, 4, 2, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 138, 248,
        255, 0, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 32, 0, 0, 0, 191, 161, 0, 0, 0, 0,
        0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0, 0, 0,
        121, 163, 248, 255, 0, 0, 0, 0, 21, 3, 172, 255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7,
        1, 0, 0, 132, 2, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123, 138,
        248, 255, 0, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 40, 0, 0, 0, 191, 161, 0, 0,
        0, 0, 0, 0, 7, 1, 0, 0, 248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 133, 0, 0, 0, 112, 0,
        0, 0, 121, 163, 248, 255, 0, 0, 0, 0, 21, 3, 159, 255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0,
        0, 7, 1, 0, 0, 4, 3, 0, 0, 183, 2, 0, 0, 128, 0, 0, 0, 133, 0, 0, 0, 114, 0, 0, 0, 123,
        138, 248, 255, 0, 0, 0, 0, 7, 7, 0, 0, 48, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0,
        248, 255, 255, 255, 183, 2, 0, 0, 8, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0,
        112, 0, 0, 0, 121, 163, 248, 255, 0, 0, 0, 0, 21, 3, 146, 255, 0, 0, 0, 0, 5, 0, 141, 255,
        0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 176, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 9, 0, 0,
        0, 64, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 9, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0,
        0, 220, 3, 0, 0, 220, 3, 0, 0, 196, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4,
        0, 0, 0, 27, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 5, 0,
        0, 0, 64, 0, 0, 0, 42, 0, 0, 0, 0, 0, 0, 14, 7, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 10, 0, 0, 0, 45, 0, 0, 0, 9, 0, 0, 4, 80, 1, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0,
        53, 0, 0, 0, 17, 0, 0, 0, 128, 8, 0, 0, 61, 0, 0, 0, 19, 0, 0, 0, 192, 8, 0, 0, 71, 0, 0,
        0, 21, 0, 0, 0, 224, 8, 0, 0, 79, 0, 0, 0, 17, 0, 0, 0, 0, 9, 0, 0, 90, 0, 0, 0, 17, 0, 0,
        0, 64, 9, 0, 0, 99, 0, 0, 0, 24, 0, 0, 0, 128, 9, 0, 0, 110, 0, 0, 0, 17, 0, 0, 0, 0, 10,
        0, 0, 127, 0, 0, 0, 17, 0, 0, 0, 64, 10, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 16, 1, 0, 0, 136, 0,
        0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 146, 0, 0, 0, 4, 0, 0,
        4, 16, 1, 0, 0, 159, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 164, 0, 0, 0, 13, 0, 0, 0, 192, 7,
        0, 0, 167, 0, 0, 0, 13, 0, 0, 0, 0, 8, 0, 0, 170, 0, 0, 0, 13, 0, 0, 0, 64, 8, 0, 0, 177,
        0, 0, 0, 0, 0, 0, 8, 14, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 13, 0, 0, 0, 4, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4,
        16, 1, 0, 0, 159, 0, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 164, 0, 0, 0, 17, 0, 0, 0, 192, 7, 0,
        0, 167, 0, 0, 0, 17, 0, 0, 0, 0, 8, 0, 0, 170, 0, 0, 0, 17, 0, 0, 0, 64, 8, 0, 0, 202, 0,
        0, 0, 0, 0, 0, 8, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 17, 0, 0, 0, 4, 0, 0, 0,
        31, 0, 0, 0, 206, 0, 0, 0, 0, 0, 0, 8, 20, 0, 0, 0, 210, 0, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0,
        216, 0, 0, 0, 0, 0, 0, 8, 22, 0, 0, 0, 220, 0, 0, 0, 0, 0, 0, 8, 23, 0, 0, 0, 226, 0, 0, 0,
        0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 17, 0, 0, 0, 4, 0,
        0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 239, 0, 0, 0, 9, 0, 0, 0, 243, 0, 0,
        0, 1, 0, 0, 12, 25, 0, 0, 0, 5, 1, 0, 0, 1, 0, 0, 4, 8, 0, 0, 0, 53, 0, 0, 0, 28, 0, 0, 0,
        0, 0, 0, 0, 21, 1, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 35, 1, 0, 0, 3, 0, 0, 4, 4,
        4, 0, 0, 41, 1, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 45, 1, 0, 0, 31, 0, 0, 0, 32, 0, 0, 0, 50,
        1, 0, 0, 32, 0, 0, 0, 32, 4, 0, 0, 55, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 30, 0, 0, 0, 4, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 0, 0, 0, 31, 0, 0, 0, 4, 0, 0, 0, 7, 0, 0, 0, 60, 1, 0, 0, 0, 0, 0, 14, 29, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 30, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 66, 1,
        0, 0, 0, 0, 0, 14, 34, 0, 0, 0, 1, 0, 0, 0, 74, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0,
        4, 80, 1, 0, 0, 0, 0, 0, 14, 36, 0, 0, 0, 2, 0, 0, 0, 152, 3, 0, 0, 1, 0, 0, 15, 4, 4, 0,
        0, 33, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 157, 3, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 35, 0, 0, 0,
        0, 0, 0, 0, 4, 0, 0, 0, 165, 3, 0, 0, 1, 0, 0, 15, 16, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16,
        0, 0, 0, 171, 3, 0, 0, 1, 0, 0, 15, 0, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95,
        95, 0, 116, 121, 112, 101, 0, 109, 97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 114,
        98, 0, 112, 116, 95, 114, 101, 103, 115, 0, 111, 114, 105, 103, 95, 120, 48, 0, 115, 121,
        115, 99, 97, 108, 108, 110, 111, 0, 117, 110, 117, 115, 101, 100, 50, 0, 115, 100, 101,
        105, 95, 116, 116, 98, 114, 49, 0, 112, 109, 114, 95, 115, 97, 118, 101, 0, 115, 116, 97,
        99, 107, 102, 114, 97, 109, 101, 0, 108, 111, 99, 107, 100, 101, 112, 95, 104, 97, 114,
        100, 105, 114, 113, 115, 0, 101, 120, 105, 116, 95, 114, 99, 117, 0, 117, 115, 101, 114,
        95, 114, 101, 103, 115, 0, 117, 115, 101, 114, 95, 112, 116, 95, 114, 101, 103, 115, 0,
        114, 101, 103, 115, 0, 115, 112, 0, 112, 99, 0, 112, 115, 116, 97, 116, 101, 0, 95, 95,
        117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 108,
        111, 110, 103, 0, 117, 54, 52, 0, 115, 51, 50, 0, 95, 95, 115, 51, 50, 0, 117, 51, 50, 0,
        95, 95, 117, 51, 50, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 99,
        116, 120, 0, 107, 112, 114, 111, 98, 101, 95, 115, 121, 115, 95, 101, 120, 101, 99, 118,
        101, 0, 112, 116, 95, 114, 101, 103, 115, 95, 95, 95, 97, 114, 109, 54, 52, 0, 117, 110,
        115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 0, 101, 118, 101, 110, 116, 0, 112,
        105, 100, 0, 112, 97, 116, 104, 0, 97, 114, 103, 118, 0, 99, 104, 97, 114, 0, 100, 117,
        109, 109, 121, 0, 76, 73, 67, 69, 78, 83, 69, 0, 95, 66, 111, 111, 108, 0, 76, 73, 78, 85,
        88, 95, 72, 65, 83, 95, 83, 89, 83, 67, 65, 76, 76, 95, 87, 82, 65, 80, 80, 69, 82, 0, 47,
        104, 111, 109, 101, 47, 112, 104, 105, 110, 103, 117, 121, 101, 110, 100, 112, 47, 87, 83,
        45, 108, 105, 110, 117, 120, 47, 101, 98, 112, 102, 47, 101, 101, 45, 101, 98, 112, 102,
        47, 99, 104, 51, 95, 101, 98, 112, 102, 95, 112, 114, 111, 98, 101, 115, 47, 107, 115, 121,
        115, 99, 97, 108, 108, 47, 115, 114, 99, 47, 98, 112, 102, 47, 107, 115, 121, 115, 99, 97,
        108, 108, 95, 101, 120, 101, 99, 118, 101, 46, 98, 112, 102, 46, 99, 0, 105, 110, 116, 32,
        66, 80, 70, 95, 75, 83, 89, 83, 67, 65, 76, 76, 40, 107, 112, 114, 111, 98, 101, 95, 115,
        121, 115, 95, 101, 120, 101, 99, 118, 101, 44, 0, 32, 32, 32, 32, 115, 116, 114, 117, 99,
        116, 32, 101, 118, 101, 110, 116, 32, 42, 101, 118, 32, 32, 61, 32, 98, 112, 102, 95, 114,
        105, 110, 103, 98, 117, 102, 95, 114, 101, 115, 101, 114, 118, 101, 40, 38, 114, 98, 44,
        32, 115, 105, 122, 101, 111, 102, 40, 42, 101, 118, 41, 44, 32, 48, 41, 59, 0, 32, 32, 32,
        32, 105, 102, 32, 40, 33, 101, 118, 41, 0, 32, 32, 32, 32, 101, 118, 45, 62, 112, 105, 100,
        32, 61, 32, 98, 112, 102, 95, 103, 101, 116, 95, 99, 117, 114, 114, 101, 110, 116, 95, 112,
        105, 100, 95, 116, 103, 105, 100, 40, 41, 32, 62, 62, 32, 51, 50, 59, 0, 32, 32, 32, 32,
        98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101, 114,
        95, 115, 116, 114, 40, 101, 118, 45, 62, 112, 97, 116, 104, 44, 32, 115, 105, 122, 101,
        111, 102, 40, 101, 118, 45, 62, 112, 97, 116, 104, 41, 44, 32, 102, 105, 108, 101, 110, 97,
        109, 101, 41, 59, 0, 32, 32, 32, 32, 32, 32, 32, 32, 99, 111, 110, 115, 116, 32, 99, 104,
        97, 114, 32, 42, 97, 114, 103, 112, 32, 61, 32, 78, 85, 76, 76, 59, 0, 32, 32, 32, 32, 32,
        32, 32, 32, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115,
        101, 114, 40, 38, 97, 114, 103, 112, 44, 32, 115, 105, 122, 101, 111, 102, 40, 97, 114,
        103, 112, 41, 44, 32, 38, 97, 114, 103, 118, 91, 105, 93, 41, 59, 0, 32, 32, 32, 32, 32,
        32, 32, 32, 105, 102, 32, 40, 33, 97, 114, 103, 112, 41, 123, 0, 32, 32, 32, 32, 32, 32,
        32, 32, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97, 100, 95, 117, 115, 101,
        114, 95, 115, 116, 114, 40, 101, 118, 45, 62, 97, 114, 103, 118, 91, 105, 93, 44, 32, 115,
        105, 122, 101, 111, 102, 40, 101, 118, 45, 62, 97, 114, 103, 118, 91, 105, 93, 41, 44, 32,
        97, 114, 103, 112, 41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 114, 105, 110, 103, 98,
        117, 102, 95, 115, 117, 98, 109, 105, 116, 40, 101, 118, 44, 32, 48, 41, 59, 0, 48, 58, 48,
        58, 48, 0, 48, 58, 48, 0, 48, 58, 48, 58, 49, 0, 46, 98, 115, 115, 0, 108, 105, 99, 101,
        110, 115, 101, 0, 46, 109, 97, 112, 115, 0, 46, 107, 99, 111, 110, 102, 105, 103, 0, 107,
        115, 121, 115, 99, 97, 108, 108, 47, 101, 120, 101, 99, 118, 101, 0, 159, 235, 1, 0, 32, 0,
        0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 60, 8, 0, 0, 80, 8, 0, 0, 92, 0, 0, 0, 8, 0, 0,
        0, 180, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 26, 0, 0, 0, 16, 0, 0, 0, 180, 3, 0, 0, 131, 0, 0,
        0, 0, 0, 0, 0, 106, 1, 0, 0, 201, 1, 0, 0, 5, 104, 0, 0, 80, 0, 0, 0, 106, 1, 0, 0, 201, 1,
        0, 0, 5, 104, 0, 0, 112, 0, 0, 0, 106, 1, 0, 0, 201, 1, 0, 0, 5, 104, 0, 0, 128, 0, 0, 0,
        106, 1, 0, 0, 201, 1, 0, 0, 5, 104, 0, 0, 136, 0, 0, 0, 106, 1, 0, 0, 201, 1, 0, 0, 5, 104,
        0, 0, 160, 0, 0, 0, 106, 1, 0, 0, 201, 1, 0, 0, 5, 104, 0, 0, 176, 0, 0, 0, 106, 1, 0, 0,
        237, 1, 0, 0, 25, 116, 0, 0, 224, 0, 0, 0, 106, 1, 0, 0, 47, 2, 0, 0, 9, 120, 0, 0, 232, 0,
        0, 0, 106, 1, 0, 0, 60, 2, 0, 0, 15, 132, 0, 0, 240, 0, 0, 0, 106, 1, 0, 0, 60, 2, 0, 0,
        42, 132, 0, 0, 248, 0, 0, 0, 106, 1, 0, 0, 60, 2, 0, 0, 13, 132, 0, 0, 0, 1, 0, 0, 106, 1,
        0, 0, 108, 2, 0, 0, 33, 136, 0, 0, 16, 1, 0, 0, 106, 1, 0, 0, 108, 2, 0, 0, 5, 136, 0, 0,
        40, 1, 0, 0, 106, 1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 56, 1, 0, 0, 106, 1, 0, 0, 60, 2,
        0, 0, 15, 132, 0, 0, 64, 1, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 9, 156, 0, 0, 88, 1, 0, 0,
        106, 1, 0, 0, 12, 3, 0, 0, 14, 160, 0, 0, 96, 1, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160,
        0, 0, 104, 1, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 120, 1, 0, 0, 106, 1, 0, 0,
        32, 3, 0, 0, 9, 172, 0, 0, 144, 1, 0, 0, 106, 1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 152, 1,
        0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 51, 156, 0, 0, 176, 1, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0,
        33, 172, 0, 0, 184, 1, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 9, 156, 0, 0, 200, 1, 0, 0, 106,
        1, 0, 0, 12, 3, 0, 0, 14, 160, 0, 0, 208, 1, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0,
        0, 216, 1, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 232, 1, 0, 0, 106, 1, 0, 0, 32,
        3, 0, 0, 9, 172, 0, 0, 248, 1, 0, 0, 106, 1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 0, 2, 0, 0,
        106, 1, 0, 0, 208, 2, 0, 0, 51, 156, 0, 0, 24, 2, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172,
        0, 0, 32, 2, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 9, 156, 0, 0, 48, 2, 0, 0, 106, 1, 0, 0, 12,
        3, 0, 0, 14, 160, 0, 0, 56, 2, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 64, 2, 0, 0,
        106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 80, 2, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172,
        0, 0, 96, 2, 0, 0, 106, 1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 104, 2, 0, 0, 106, 1, 0, 0,
        208, 2, 0, 0, 51, 156, 0, 0, 128, 2, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 136,
        2, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 9, 156, 0, 0, 152, 2, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0,
        14, 160, 0, 0, 160, 2, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 168, 2, 0, 0, 106,
        1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 184, 2, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172, 0, 0,
        200, 2, 0, 0, 106, 1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 208, 2, 0, 0, 106, 1, 0, 0, 208,
        2, 0, 0, 51, 156, 0, 0, 232, 2, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 240, 2, 0,
        0, 106, 1, 0, 0, 208, 2, 0, 0, 9, 156, 0, 0, 0, 3, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 14,
        160, 0, 0, 8, 3, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 16, 3, 0, 0, 106, 1, 0, 0,
        32, 3, 0, 0, 33, 172, 0, 0, 32, 3, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172, 0, 0, 48, 3, 0,
        0, 106, 1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 56, 3, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 51,
        156, 0, 0, 80, 3, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 88, 3, 0, 0, 106, 1, 0,
        0, 208, 2, 0, 0, 9, 156, 0, 0, 104, 3, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 14, 160, 0, 0, 112,
        3, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 120, 3, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0,
        33, 172, 0, 0, 136, 3, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172, 0, 0, 152, 3, 0, 0, 106, 1,
        0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 160, 3, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 51, 156, 0, 0,
        176, 3, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 184, 3, 0, 0, 106, 1, 0, 0, 208, 2,
        0, 0, 9, 156, 0, 0, 208, 3, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 14, 160, 0, 0, 216, 3, 0, 0,
        106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 224, 3, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172,
        0, 0, 240, 3, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172, 0, 0, 0, 4, 0, 0, 106, 1, 0, 0, 105,
        3, 0, 0, 5, 180, 0, 0, 24, 4, 0, 0, 106, 1, 0, 0, 201, 1, 0, 0, 5, 104, 0, 0, 40, 4, 0, 0,
        106, 1, 0, 0, 201, 1, 0, 0, 5, 104, 0, 0, 64, 4, 0, 0, 106, 1, 0, 0, 237, 1, 0, 0, 25, 116,
        0, 0, 112, 4, 0, 0, 106, 1, 0, 0, 47, 2, 0, 0, 9, 120, 0, 0, 120, 4, 0, 0, 106, 1, 0, 0,
        60, 2, 0, 0, 15, 132, 0, 0, 128, 4, 0, 0, 106, 1, 0, 0, 60, 2, 0, 0, 42, 132, 0, 0, 136, 4,
        0, 0, 106, 1, 0, 0, 60, 2, 0, 0, 13, 132, 0, 0, 144, 4, 0, 0, 106, 1, 0, 0, 108, 2, 0, 0,
        33, 136, 0, 0, 160, 4, 0, 0, 106, 1, 0, 0, 108, 2, 0, 0, 5, 136, 0, 0, 184, 4, 0, 0, 106,
        1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 200, 4, 0, 0, 106, 1, 0, 0, 60, 2, 0, 0, 15, 132, 0,
        0, 208, 4, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 9, 156, 0, 0, 232, 4, 0, 0, 106, 1, 0, 0, 12,
        3, 0, 0, 14, 160, 0, 0, 240, 4, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 248, 4, 0,
        0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 8, 5, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172,
        0, 0, 32, 5, 0, 0, 106, 1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 40, 5, 0, 0, 106, 1, 0, 0,
        208, 2, 0, 0, 51, 156, 0, 0, 64, 5, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 72, 5,
        0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 9, 156, 0, 0, 88, 5, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 14,
        160, 0, 0, 96, 5, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 104, 5, 0, 0, 106, 1, 0,
        0, 32, 3, 0, 0, 33, 172, 0, 0, 120, 5, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172, 0, 0, 136,
        5, 0, 0, 106, 1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 144, 5, 0, 0, 106, 1, 0, 0, 208, 2, 0,
        0, 51, 156, 0, 0, 168, 5, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 176, 5, 0, 0,
        106, 1, 0, 0, 208, 2, 0, 0, 9, 156, 0, 0, 192, 5, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 14, 160,
        0, 0, 200, 5, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 208, 5, 0, 0, 106, 1, 0, 0,
        32, 3, 0, 0, 33, 172, 0, 0, 224, 5, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172, 0, 0, 240, 5,
        0, 0, 106, 1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 248, 5, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0,
        51, 156, 0, 0, 16, 6, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 24, 6, 0, 0, 106, 1,
        0, 0, 208, 2, 0, 0, 9, 156, 0, 0, 40, 6, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 14, 160, 0, 0,
        48, 6, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 56, 6, 0, 0, 106, 1, 0, 0, 32, 3, 0,
        0, 33, 172, 0, 0, 72, 6, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172, 0, 0, 88, 6, 0, 0, 106,
        1, 0, 0, 175, 2, 0, 0, 21, 152, 0, 0, 96, 6, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 51, 156, 0,
        0, 120, 6, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 128, 6, 0, 0, 106, 1, 0, 0, 208,
        2, 0, 0, 9, 156, 0, 0, 144, 6, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 14, 160, 0, 0, 152, 6, 0,
        0, 106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 160, 6, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33,
        172, 0, 0, 176, 6, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172, 0, 0, 192, 6, 0, 0, 106, 1, 0,
        0, 175, 2, 0, 0, 21, 152, 0, 0, 200, 6, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 51, 156, 0, 0,
        224, 6, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 232, 6, 0, 0, 106, 1, 0, 0, 208, 2,
        0, 0, 9, 156, 0, 0, 248, 6, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 14, 160, 0, 0, 0, 7, 0, 0,
        106, 1, 0, 0, 12, 3, 0, 0, 13, 160, 0, 0, 8, 7, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172,
        0, 0, 24, 7, 0, 0, 106, 1, 0, 0, 32, 3, 0, 0, 9, 172, 0, 0, 40, 7, 0, 0, 106, 1, 0, 0, 175,
        2, 0, 0, 21, 152, 0, 0, 48, 7, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 51, 156, 0, 0, 64, 7, 0,
        0, 106, 1, 0, 0, 32, 3, 0, 0, 33, 172, 0, 0, 72, 7, 0, 0, 106, 1, 0, 0, 208, 2, 0, 0, 9,
        156, 0, 0, 96, 7, 0, 0, 106, 1, 0, 0, 12, 3, 0, 0, 14, 160, 0, 0, 104, 7, 0, 0, 106, 1, 0,
        0, 12, 3, 0, 0, 13, 160, 0, 0, 16, 0, 0, 0, 180, 3, 0, 0, 5, 0, 0, 0, 32, 0, 0, 0, 12, 0,
        0, 0, 136, 3, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 27, 0, 0, 0, 142, 3, 0, 0, 0, 0, 0, 0, 96, 0,
        0, 0, 12, 0, 0, 0, 146, 3, 0, 0, 0, 0, 0, 0, 40, 4, 0, 0, 12, 0, 0, 0, 146, 3, 0, 0, 0, 0,
        0, 0, 48, 4, 0, 0, 27, 0, 0, 0, 142, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0,
        200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0,
        0, 0, 0, 0, 32, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0,
        0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        40, 2, 0, 0, 0, 0, 0, 0, 120, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 33, 0, 0, 0, 8, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 160, 9, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 9, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 9, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 166, 0, 0, 0, 9, 0,
        0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 184, 9, 0, 0, 0, 0, 0, 0, 48, 0, 0,
        0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0,
        186, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 232, 9, 0, 0, 0,
        0, 0, 0, 184, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 191, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        160, 17, 0, 0, 0, 0, 0, 0, 204, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
