// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

#[path = "ksyscall_execve.skel.rs"]
mod ksyscall_execve_skel;
pub use ksyscall_execve_skel::*;
